### ISSUE TITLE
onExpansionCollapsed being called with wrong boolean

### ISSUE THREAD

**Issue by tsuharesu** [bignerdranch/expandable-recycler-view#103]
https://github.com/bignerdranch/expandable-recycler-view/blob/master/expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/ViewHolder/ParentViewHolder.java#L148

It is being called with `false` on Expand, but the method says it should be called with `true` when expanding:
https://github.com/bignerdranch/expandable-recycler-view/blob/master/expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/ViewHolder/ParentViewHolder.java#L86

**Comment by dgreenhalgh** [comment]
Hey @tsuharesu, thanks for pointing this out. The `expanded` parameter of `onExpansionToggled` refers to the state of the list item before expansion/collapse is triggered.

We'll clarify the documentation here.

**Comment by tsuharesu** [comment]
Thanks :)
