### ISSUE TITLE
mParentDropDownArrow enable/disable

### ISSUE THREAD

**Issue by XxGoliathusxX** [bignerdranch/expandable-recycler-view#106]
Has someone an idea how to remove the dropdown-arrow (make it invisible)?

**Comment by paul-turner** [comment]
Dynamically? or all together have it not show up?

**Comment by XxGoliathusxX** [comment]
Dynamically

**Comment by paul-turner** [comment]
can do so in `onBindParentViewHolder`, just set your view to invisible.
Or if you need to do it based on expansion/collapsing can override `onExpansionToggled` in your ParentViewHolder

I guess it's more of a question of when you want to do it, then can help with the answer.

**Comment by XxGoliathusxX** [comment]
When you delete an item or move it and that occurs that the childlist is empty. Then no arrow is necassary and confusing.

**Comment by paul-turner** [comment]
Probably need to kick off a notifyParentItemChanged then to trigger a rebind and make the arrow go away in that case.

Either that or fetch the view through the recyclerview and set it manually yourself (not recommended)

**Comment by XxGoliathusxX** [comment]
Ok, thats seems difficult maybe ill find sth else

**Comment by Vengat121** [comment]
how to disable arrow permanently
