### ISSUE TITLE
item selection onLongPress?

### ISSUE THREAD

**Issue by TheLoyalCruel** [bignerdranch/expandable-recycler-view#107]
I'm using Vertical Linear Sample of demo app...
is there any sample on how to (highlight) select items of recyclerView onLongPress?
thanks...

**Comment by XxGoliathusxX** [comment]
Sure. Implement ItemTouchHelper interface and overwrite onItemSelected(). On the itemView:
 itemView.setBackgroundColor(COLOR);

**Comment by TheLoyalCruel** [comment]
can you give me a sample?
I dont know how to do this...
thanks

**Comment by XxGoliathusxX** [comment]
This tutorial is very useful. Only implement what you need:
https://medium.com/@ipaulpro/drag-and-swipe-with-recyclerview-b9456d2b1aaf

**Comment by XxGoliathusxX** [comment]
On Page 2 Section: "Indicating the Selected View".

**Comment by TheLoyalCruel** [comment]
I see... but are you sure it is about selecting the items?
I want to be able to select the first item by long press and the other items by a simple click (something like contextual action bar on it) when the contextual menu is opened the expanding of should be disabled and do some operations inside the app with context (like deleting or moving items inside a view pager...
oh Im sorry... I ask too much...

**Comment by TheLoyalCruel** [comment]
I see... but are you sure it is about selecting the items?
I want to be able to select the first item by long press and the other items by a simple click (something like contextual action bar on it) when the contextual menu is opened the expanding of should be disabled and do some operations inside the app with context (like deleting or moving items inside a view pager...
oh Im sorry... I ask too much...

**Comment by XxGoliathusxX** [comment]
Hmm my english is not the best. For me it works. When i click on a parent or a child (Longpress) the color on this particular item changes to a bit darker one. I dont understand what you mean with 
"and the other items by a simple click (something like contextual action bar on it) when the contextual menu is opened the expanding of should be disabled and do some operations inside the app with context (like deleting or moving items inside a view pager..."
