### ISSUE TITLE
notifyParentItemChanged (2.0.2)

### ISSUE THREAD

**Issue by rafaelmeteoro** [bignerdranch/expandable-recycler-view#112]
A problem occurred when updated to 2.0.2

I am using ExpandCollapseListener and when onListItemExpandedis is called I update one parent item and call notifyParentItemChanged.

When the item is expanded appear two child items. Sometimes three.

In version 2.0.1 this does not happen

**Comment by paul-turner** [comment]
Good catch, I think this is due to the timing of when we call onListItemExpanded. Will try to have a fix by tomorrow.

Thank you @rafaelmeteoro
