### ISSUE TITLE
Header Parent View

### ISSUE THREAD

**Issue by rstel** [bignerdranch/expandable-recycler-view#121]
I believe giving the developer the ability to create a header view for the Parent View Holder would be an awesome feature. The library is a breeze to use and with this feature implemented it would be the icing on the cake.

**Comment by paul-turner** [comment]
I don't know that we will do headers specifically. However having different view types will probably help give the user this ability. That effort is being tracked in #108, after that is completed we can revisit the  need of headers and see if we need to give it a specific solution.

**Comment by rstel** [comment]
Great. I'll be playing around with the source code to see if I can get a
solution working where the first parent list item is the header and loads a
custom view. If my solution meets the requirements of #108 I'll be sure to
let you guys know :-). I love the library by the way. It was extremely easy
to setup and get working.

**Comment by paul-turner** [comment]
@rstel thanks for the kind words, good luck with your changes!

**Comment by Mauker1** [comment]
I was also wondering if this *possible* feature was going to be released. I have some views that I could call the "header" of my Activity, and below them I have the RV. Thing is, the header is already inside a NestedScrollView, but the RV also have its own scroll. If feels a little weird to me.

**Comment by paul-turner** [comment]
@Mauker1 would it be enough to have your header views as different views placed between the parent views? I don't think this library will ever do something like floating headers so making sure I understand what people are expecting.
