### ISSUE TITLE
Crash Restoring State

### ISSUE THREAD

**Issue by paul-turner** [bignerdranch/expandable-recycler-view#122]
From #90:
> I used the code you provided in my MyExpandableAdapter.java

>Everything works fine but after i browse the application, change the device configuration to landscape and switch to another application there was an error occurred related to 
ArrayIndexOutOfBound in the mExpandableAdapter.onRestoreInstanceState(savedInstanceState);

>Caused by: java.lang.IndexOutOfBoundsException: Invalid index 20, size is 20 
at com.bignerdranch.expandablerecyclerview.Adapter.ExpandableRecyclerAdapter.getListItem(ExpandableRecyclerAdapter.java:490)
at com.bignerdranch.expandablerecyclerview.Adapter.ExpandableRecyclerAdapter.onRestoreInstanceState(ExpandableRecyclerAdapter.java:445)
at com.eyey.android.eyeynews.ui.MainActivity.onRestoreInstanceState(MainActivity.java:87)

**Comment by paul-turner** [comment]
Also from #90 
Question:
>does the crash still occur if you don't have the code I provided? it seems like this issue may be separate from the changes I suggest.

Reply:
>I just tested it again, thing a bit different, When I put your code things work fine even i change device configuration and browse around however after a while of running by changing back and forth the applications. The same error occurred.

>When i don't use your code, things work fine.

>I think the out of bound part was the problem. 
Caused by: java.lang.IndexOutOfBoundsException: Invalid index 20, size is 20
There is only 20 objects, and I suppose the start index is 0.
and why in onRestoreInstanceState method the getListItem method try to access the object 20th.

**Comment by vsay01** [comment]
I tested it again. 
It crash for this situation:
after i run the application, if the child view is expanded there will be no problem when rotate devices; however if all the child view collapsed and i try to rotate the device then above crash (Index out of bound) will occurred.

There are two sample in your repository, the crime one has no problem however the vertical and horizontal sample produce error as above mention situation.

**Comment by paul-turner** [comment]
@vsay01 thanks for the information, I've pushed a snapshot with what I think is the fix. Could you give it a try and see if it fixes your problems (fixed the crash in the samples).
Use:
```
compile 'com.bignerdranch.android:expandablerecyclerview:2.0.4-SNAPSHOT'
```

**Comment by vsay01** [comment]
@paul-turner 
I used this: android:expandablerecyclerview:2.0.4-SNAPSHOT'
When I sync project with gradle files
Error:(36, 13) Failed to resolve: com.bignerdranch.android:expandablerecyclerview:2.0.4-SNAPSHOT

**Comment by paul-turner** [comment]
Sorry forgot one step:

Add Sonatype's snapshots to your repositories closure in the root `build.gradle`:
```gradle
allprojects {
    repositories {
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
}
```

**Comment by vsay01** [comment]
Thank @paul-turner 
I used the snapshot above in sample horizontal, vertical sample, and my project it fix above issue.
So are you going to release the 2.0.4 soon?

**Comment by paul-turner** [comment]
Yes will probably release sometime tomorrow, thanks for your help

**Comment by vsay01** [comment]
@paul-turner Thank for a useful library :+1:

**Comment by paul-turner** [comment]
@vsay01 Took a little longer than anticipated (the first fix still had some problems). But 2.0.4 is released now, should pop into maven in the next couple hours.
