### ISSUE TITLE
How to use notifyparentitemisterted ?

### ISSUE THREAD

**Issue by symbicort** [bignerdranch/expandable-recycler-view#123]
I am really lost in how to implement notifyparentiteminserted. The way i know is add item to list in adapter then notify the change. I couldnt figure out how to add item to parentlistitem

thanks in advance

**Comment by paul-turner** [comment]
@symbicort You can either keep a reference to the `ParentItemList` or call `getParentItemList()` on the adapter and then insert your item. We have a sample showing an example at:
[HorizontalLinearRecyclerViewSampleActivity.java#L172](https://github.com/bignerdranch/expandable-recycler-view/blob/master/app/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/horizontal/HorizontalLinearRecyclerViewSampleActivity.java#L172)
or
[HorizontalLinearRecyclerViewSampleActivity.java#L205](https://github.com/bignerdranch/expandable-recycler-view/blob/master/app/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/horizontal/HorizontalLinearRecyclerViewSampleActivity.java#L205)

Hope that helps!

**Comment by symbicort** [comment]
well didnt think that adapter would still take the list as reference. thank you. it worked!
