### ISSUE TITLE
How do I know if parent is expanded

### ISSUE THREAD

**Issue by silviahisham** [bignerdranch/expandable-recycler-view#125]
I'm using ```onExpansionToggled``` to detect if a parent item is expanded so that I can change something in its view, but when I scroll the recyclerview, the inital view is back again, my question is how can I know that a parent is expanded or not in ```onBindParentViewHolder ```  so that I can keep its state?

**Comment by paul-turner** [comment]
Hi @silviahisham,
In `onBindParentViewHolder` you are given a `ParentViewHolder` which we have already updated the state of whether or not that view is expanded. So you can call `isExpanded()` and get your state when setting up the view with every bind.

**Comment by silviahisham** [comment]
Thank you it worked.
