### ISSUE TITLE
How to animate view in the parent when parent is expanded?

### ISSUE THREAD

**Issue by symbicort** [bignerdranch/expandable-recycler-view#126]
It's a bit noobish question again. Thanks in advance

**Comment by paul-turner** [comment]
Hi @symbicort,
You can look at our example where we animate the expand icon:
[HorizontalParentViewHolder](https://github.com/bignerdranch/expandable-recycler-view/blob/master/app/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/horizontal/HorizontalParentViewHolder.java)

There is one key method:
[onExpansionToggled](https://github.com/bignerdranch/expandable-recycler-view/blob/master/app/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/horizontal/HorizontalParentViewHolder.java#L86)

This will get triggered any time there's a change in expansion state and let you do any animation you want hopefully.

Let me know if you run into problems.

**Comment by symbicort** [comment]
Thanks, i got it working.
