### ISSUE TITLE
Custom child view type

### ISSUE THREAD

**Issue by nguyenhoanglam** [bignerdranch/expandable-recycler-view#131]
I want to set custom child view depending on child type. For example, item type and progressbar type. How can I do that?

**Comment by paul-turner** [comment]
unfortunately not supported very well, we are using #108 to track this future feature

**Comment by paul-turner** [comment]
With PR #234 we now should have better support for multiple views. I would love feedback before we make a release! Please leave feedback in the original issue tracking this feature #108 

You can see the 3.0.0 code [here](https://github.com/bignerdranch/expandable-recycler-view/tree/dev-3.0.0)

The [recipe sample](https://github.com/bignerdranch/expandable-recycler-view/blob/dev-3.0.0/sampleapp/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/vertical/RecipeAdapter.java) shows a quick example of using multiple view types

To use the snapshot you will need to add the following to your app's `build.gradle`:

```
compile 'com.bignerdranch.android:expandablerecyclerview:3.0.0-SNAPSHOT'
```

You will also need to add Sonatype's snapshots to your repositories closure in the root `build.gradle`:
 ```gradle
 allprojects {
     repositories {
         maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
     }
 }
 ```

Thank you!
