### ISSUE TITLE
Child views not seen

### ISSUE THREAD

**Issue by Jyoshna27** [bignerdranch/expandable-recycler-view#133]
If recyclerViewAdapter is set to recyclerView, child views are not seen when parent views are clicked. But if  expandablelistadapter is set to recyclerView, child views are seen, but parent views are seen from header not from below tab.How can i set recyclerViewAdapter to recyclerView  using RecyclerMaterialAdapter so that parent views are seen below tabs and child views are seen when clicked.

**Comment by paul-turner** [comment]
Hi @Jyoshna27, I am not familiar with RecyclerMaterialAdapter could you provide a link?

Also, you refer to `recyclerViewAdapter` but it's unclear what that means in this context (are you extending our adapter or some other?), it might help if you provide some sample code of your situation first.
