### ISSUE TITLE
Change background colour of the expanded row and change back when collapse

### ISSUE THREAD

**Issue by vsay01** [bignerdranch/expandable-recycler-view#134]
Hi,

For my case at a time only one row can be expanded.

How can I change the background colour of the expanded row of the expandable-recycler-view?

Then, change it back to normal background colour when the row is collapsed?

Thank,

**Comment by paul-turner** [comment]
Hi @vsay01, you should be able to use `onExpansionToggled(boolean)` method in your `ParentViewHolder` and change your view background color there.

**Comment by vsay01** [comment]
Thank @paul-turner

**Comment by paul-turner** [comment]
@vsay01 you will probably have to register a listener to the expanding and send a `notifyChildItemRangeChanged` to the adapter to signify a change is happened.

Although you might say that children will never be shown if it is collapsed so they will only ever need to be the expanded color

**Comment by joydeepsaha05** [comment]
@vsay01 Could you please show how you implemented it? I'm having problems getting the parent layout whose color needs to be changed.
