### ISSUE TITLE
Some times child view is not expanding

### ISSUE THREAD

**Issue by bGorle** [bignerdranch/expandable-recycler-view#135]
When I'm clicking the parent views rapidly after some clicks child view is not expanding.

**Comment by paul-turner** [comment]
@bGorle are you saying that after some rapid clicks, the parent view gets in a state where taps on the parent view will not trigger expansion ever? Or that some of the rapid clicks are lost?

**Comment by moloti** [comment]
@bGorle I think this problem comes up if your icon, which should trigger the expansion, is too small and then you miss the view. It looks like you hit it but you actually dont hit it, just make the icon a bit larger and your child view is always expanding.
