### ISSUE TITLE
Is there any way I can get the RecyclerView height to expand or collapse depending on what is being shown?

### ISSUE THREAD

**Issue by GYberkeley** [bignerdranch/expandable-recycler-view#141]
At the moment, it seems that when I expand the RecyclerView, it is simply wrapping its contents to a constrained height. In other words, I expect it to push the views below it downwards, but it is not doing that. How can I adjust the recyclerview's layout height dynamically?

**Comment by paul-turner** [comment]
Hi @GYberkeley,
I think this is a limitation with RecyclerView and the default linear layout manager(LLM). A previous user tried a different LLM in #132 but it did not seem to interact with adding/removing of items very well.

I currently do not know of a way to have RecyclerView dynamically change the viewport when items are expanded, most of my RecyclerViews have a fixed height to them.

**Comment by lbx2015** [comment]
I have the same issue two, I have a horizontal RecyclerView when the item is clicked, the view become bigger than others, but the height of RecyclerView not changed accordingly each time. How can we solved this. For the moment I set a minHeight to the recyclerView in order to showing all contents.
