### ISSUE TITLE
Parent does not stay the way it should when expanding/collapsing

### ISSUE THREAD

**Issue by sthuber90** [bignerdranch/expandable-recycler-view#144]
When I animate the parent expanding and collapsing using `onExpansionToggled(boolean)` and then scrolling the list the changes made inside the `onExpansionToggled(boolean)` method, e.g. changing the icon, are no longer set. Even though in the animation I specify:
```xml
    android:fillAfter="true"
    android:fillEnabled="true"
```
Setting the new value for the icon in an custom `AnimationListener` in the `onAnimationEnd(Animation)` method doesn't change anything.

**Comment by paul-turner** [comment]
Hi @sthuber90 

It seems right now that you have the code to change the icon in response to a press, but on scrolling back and forth that view is being reused and reset elsewhere to the previous icon.

I think the problem is with your initial binding of the view. In `ParentViewHolder` you are given a method `isExpanded()` which can tell you whether the row is currently expanded or not. Based on this you need to make sure that the icon is changed accordingly (without animation) every time that you bind the view.

**Comment by sthuber90** [comment]
Currently my `ParentViewHolder` looks like this
``` java
 public class LocationParentViewHolder extends ParentViewHolder {
        public View mParentView;
        public TextView mParentTextView;
        public TextView mIcon;

        public LocationParentViewHolder(View itemView)  {
            super(itemView);
            mParentView = itemView;
            mParentTextView = (TextView) itemView.findViewById(R.id.parent_list_text);
            mIcon = (TextView) itemView.findViewById(R.id.parent_list_icon);
            mIcon.setTypeface(FontManager.getTypeface(itemView.getContext(), FontManager.FONTAWESOME));

        }

        @Override
        public void onExpansionToggled(boolean expanded) {
            super.onExpansionToggled(expanded);
            Animation rotation = null;

            if(expanded) {
                rotation = AnimationUtils.loadAnimation(mParentView.getContext(), R.anim.collapse_rotator);
                mParentTextView.setTextColor(Color.parseColor("#B5B5B5"));
                mIcon.setTextColor(Color.parseColor("#B5B5B5"));
            } else {
                rotation = AnimationUtils.loadAnimation(mParentView.getContext(), R.anim.expand_rotator);
                mParentTextView.setTextColor(Color.parseColor("#D5C800"));
                mIcon.setTextColor(Color.parseColor("#D5C800"));
            }

            mIcon.startAnimation(rotation);
        }
    }
```

And I use the code provided by you in #90 to make sure that only one parent is expanded.

Following happens with my current implementation:
- I click one item: It expands and animates like expected (the icon rotates and the color of icon and text change in parent). Then I scroll and see that the color of the icon and text also changed on another item on the next "page" (page in the meaning that I don't see the originally expanded item no more)
- I scroll  back up and the originally expanded item is still expanded, but the color of the icon and text as well as the orientation of the icon are back to their initial state.

The way I bind my parent view seems to be the one you explained in your documentation:
``` java
@Override
    public void onBindParentViewHolder(final LocationParentViewHolder parentViewHolder, final int position, final ParentListItem parentListItem) {
        LocationParent parent = (LocationParent) parentListItem;
        parentViewHolder.mParentTextView.setText(parent.getCity());

//        mParentViewHolderMap.put(position, parentViewHolder.mParentView);

//        if(parentViewHolder.isExpanded()) {
//            parentViewHolder.mParentTextView.setTextColor(ContextCompat.getColor(context, R.color.textAccentColor));
//            parentViewHolder.mIcon.setText(R.string.fa_chevron_circle_down);
//            parentViewHolder.mIcon.setTextColor(ContextCompat.getColor(context, R.color.textAccentColor));
//        }
    }

Where would you like me to try your solution with `isExpanded()`. 

Thanks in advance for your support.
```

**Comment by paul-turner** [comment]
Thanks for the info.

It seems you have some of the code there but not fully complete, I'd recommend something like the following (used random variables for you to fill in the correct values you want):
```
@Override
    public void onBindParentViewHolder(final LocationParentViewHolder parentViewHolder, final int position, final ParentListItem parentListItem) {
        LocationParent parent = (LocationParent) parentListItem;
        parentViewHolder.mParentTextView.setText(parent.getCity());

//        mParentViewHolderMap.put(position, parentViewHolder.mParentView);

        if(parentViewHolder.isExpanded()) {
            parentViewHolder.mParentTextView.setTextColor(EXPANDED_COLOR);
            parentViewHolder.mIcon.setText(EXPANDED_TEXT);
            parentViewHolder.mIcon.setTextColor(EXPANDED_ICON_COLOR);
        } else {
            parentViewHolder.mParentTextView.setTextColor(COLLAPSED_COLOR);
            parentViewHolder.mIcon.setText(COLLAPSED_TEXT);
            parentViewHolder.mIcon.setTextColor(COLLAPSED_ICON_COLOR);
        }
    }
```

I'd also recommend reading a little bit more about recycler view and the process of creating and binding views, focusing on how recycler view will reuse a view for different rows.

Lets see if that gives you the look you need!

**Comment by sthuber90** [comment]
Thank you. It's working as expected now. Don't know why I didn't get to that conclusion by myself :+1:
