### ISSUE TITLE
Only have one expanded parent at max

### ISSUE THREAD

**Issue by sthuber90** [bignerdranch/expandable-recycler-view#145]
Hi,

is there a way that I can have only one expanded parent and when I click another parent all the ones that have not been clicked will collapse. Please keep in mind that I would like an expanded parent to have another style e.g. other icon, text color, than the collapsed parent.

Is this possible in any way? I tried using `onExpansionToggled(boolean)` method for that, also in compination with `onListItemCollapsed(int)` and `onListItemExpanded(int)`. But this caused a funny effect that when I clicked on one parent and then scrolled the list, the styles were also applied to other parent items in the list, but they were not expanded, like the one I actually clicked on.

**Comment by paul-turner** [comment]
I think #90 will help you a lot, it offers a solution that seems very similar (if not exactly) what you are looking for.

If not we can try to see what might be better for you after trying that solution.

**Comment by sthuber90** [comment]
#90 helped to make sure that only one parent list item is expanded. Thanks.
