### ISSUE TITLE
using ItemTouchHelper for drag and drop.

### ISSUE THREAD

**Issue by BlackAngel1991** [bignerdranch/expandable-recycler-view#155]
is there a way to use ItemTouchHelper with this library?
i want to reorder or change items parent with drag and drop.

**Comment by paul-turner** [comment]
Hi @BlackAngel1991, curious if you found a solution to this? My first guess is that it is possible but may be a little harder than with a normal adapter/RecyclerView.

**Comment by XxGoliathusxX** [comment]
@BlackAngel1991 @paul-turner Its possible:
**https://www.youtube.com/watch?v=MxLBMdSdI4g**

**Comment by paul-turner** [comment]
@XxGoliathusxX Awesome thanks for sharing! Glad this library didn't get in your way too much :)
