### ISSUE TITLE
Swipe to remove with expanded items

### ISSUE THREAD

**Issue by keigezellig** [bignerdranch/expandable-recycler-view#160]
First of all, thanks for such a nice library. I have a small question though,
I created a ItemTouchHelper for my expandable recycler view to support swipe to remove, but i only allow swiping for parent items. When I in this way swipe an item when all items are collapsed, it works fine, but when one or more items are expanded things don't work as expected ('orphaned' child items stay behind, crashes)
This is the code of the TouchHelper:
```java
public class AlertListTouchHelper extends ItemTouchHelper.SimpleCallback 
{
    private AlertExpandableRecycleAdapter alertRecycleAdapter;

    public AlertListTouchHelper(AlertExpandableRecycleAdapter alertRecycleAdapter)
    {
        super(ItemTouchHelper.UP | ItemTouchHelper.DOWN, ItemTouchHelper.LEFT | ItemTouchHelper.RIGHT);
        this.alertRecycleAdapter = alertRecycleAdapter;
    }

    @Override
    public void onSwiped(RecyclerView.ViewHolder viewHolder, int direction) 
    {
        AlertListItemViewModel parent = (AlertListItemViewModel)alertRecycleAdapter.getParentItemList().get(viewHolder.getAdapterPosition());
        alertRecycleAdapter.collapseParent(parent);
        int idx = alertRecycleAdapter.getParentItemList().indexOf(parent);
        Log.d(getClass().getName(),"Swiped: "+idx);
        alertRecycleAdapter.notifyParentItemRemoved(idx);
    }

    @Override
    public int getSwipeDirs(RecyclerView recyclerView, RecyclerView.ViewHolder viewHolder)
    {
        if (viewHolder instanceof AlertListItemDetailViewHolder) return 0;
        return super.getSwipeDirs(recyclerView, viewHolder);
    }
}

```
`AlertListItemViewHolder` is the parent viewholder
`AlertListItemDetailViewHolder` is the child viewholder
`AlertListItemViewModel` is the parent adapter item
`AlertListItemDetailViewModel` is the child adapter item

As you can see in the code snippet, i tried to first collapse the parent and then try to get the position of the parent item again since i have a feeling that expanding/collapsing messes with the adapter positions, but this isn't working. Basically, what i need is the position in the **parent item list**. Any idea how to accomplish this?

Thanks

**Comment by paul-turner** [comment]
I think the problem may be with this line of code:
```java
AlertListItemViewModel parent = (AlertListItemViewModel)alertRecycleAdapter.getParentItemList().get(viewHolder.getAdapterPosition());
```

the adapter position is not equal to the current parent position. For example, if you have a list displaying as:
```
Expanded Parent 1
    Child 1
    Child 2
    Child 3
CollapsedParent 2
CollapsedParent 3
```
getAdapterPosition inside of `CollapsedParent 3` would return 5 instead of the parent position of 2 that it is within the `ParentItemList`

Right now you would have to store the position information yourself, #157 is tracking the effort to improve  this. It's been a popular topic lately so will likely be working on this soon.

Let me know If I can help explain anything else.

**Comment by paul-turner** [comment]
With #171 there is now a snapshot build that should let you access more information from the `ViewHolder`s:
- Added ParentViewHolder methods:
    - `getParentListItem()`
    - `getParentAdapterPosition()`
- Added ChildViewHolder methods:
    - `getChildListItem()`
    - `getParentAdapterPosition()`
    - `getChildAdapterPosition()`

This required changing the package location so bumped up the version to 3.0.0, which means this will probably be a snapshot for a bit as we get more features in for the library.
Instructions on how to get the snapshot are available in the `README` at https://github.com/bignerdranch/expandable-recycler-view/tree/dev

Let me know what you think.

**Comment by ravinada** [comment]
> First of all, thanks for such a nice library. I have a small question though,
> I created a ItemTouchHelper for my expandable recycler view to support swipe to remove, but i only allow swiping for parent items. When I in this way swipe an item when all items are collapsed, it works fine, but when one or more items are expanded things don't work as expected ('orphaned' child items stay behind, crashes)
> This is the code of the TouchHelper:
> 
> ```java
> public class AlertListTouchHelper extends ItemTouchHelper.SimpleCallback 
> {
>     private AlertExpandableRecycleAdapter alertRecycleAdapter;
> 
>     public AlertListTouchHelper(AlertExpandableRecycleAdapter alertRecycleAdapter)
>     {
>         super(ItemTouchHelper.UP | ItemTouchHelper.DOWN, ItemTouchHelper.LEFT | ItemTouchHelper.RIGHT);
>         this.alertRecycleAdapter = alertRecycleAdapter;
>     }
> 
>     @Override
>     public void onSwiped(RecyclerView.ViewHolder viewHolder, int direction) 
>     {
>         AlertListItemViewModel parent = (AlertListItemViewModel)alertRecycleAdapter.getParentItemList().get(viewHolder.getAdapterPosition());
>         alertRecycleAdapter.collapseParent(parent);
>         int idx = alertRecycleAdapter.getParentItemList().indexOf(parent);
>         Log.d(getClass().getName(),"Swiped: "+idx);
>         alertRecycleAdapter.notifyParentItemRemoved(idx);
>     }
> 
>     @Override
>     public int getSwipeDirs(RecyclerView recyclerView, RecyclerView.ViewHolder viewHolder)
>     {
>         if (viewHolder instanceof AlertListItemDetailViewHolder) return 0;
>         return super.getSwipeDirs(recyclerView, viewHolder);
>     }
> }
> ```
> 
> `AlertListItemViewHolder` is the parent viewholder
> `AlertListItemDetailViewHolder` is the child viewholder
> `AlertListItemViewModel` is the parent adapter item
> `AlertListItemDetailViewModel` is the child adapter item
> 
> As you can see in the code snippet, i tried to first collapse the parent and then try to get the position of the parent item again since i have a feeling that expanding/collapsing messes with the adapter positions, but this isn't working. Basically, what i need is the position in the **parent item list**. Any idea how to accomplish this?
> 
> Thanks

please provide some suggestion for expandableRecycler view swipe left right
