### ISSUE TITLE
Scroll bar not visible

### ISSUE THREAD

**Issue by MizzleDK** [bignerdranch/expandable-recycler-view#161]
It seems like it's impossible to show a scroll bar when using the library. Can you confirm?

**Comment by paul-turner** [comment]
Just tested our sample now by setting:
```xml
<android.support.v7.widget.RecyclerView
        android:id="@+id/recyclerview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="vertical"/>
```
and could see the scrollbars, this library shouldn't affect anything with the RecyclerView display (all it does is abstract the idea of parents and children at the adapter level). 

Good luck!

**Comment by MizzleDK** [comment]
Yeah, I thought it was rather weird that the library would have any effect on this. I've already tried using the android:scrollbars="vertical" attribute, but to no luck. Oh well, thanks for responding!

**Comment by paul-turner** [comment]
If you can get an example recreating the issue I wouldn't mind taking a peek, who knows maybe it is something wrong with the lib strangely. Maybe it's a device issue, does it also not show on the emulator? And just to be clear I'm only seeing the scrollbar when the user scrolls, by default they hide when it is stable.
