### ISSUE TITLE
getAdapterPosition return wrong position in ParentViewHolder

### ISSUE THREAD

**Issue by hrsalehi** [bignerdranch/expandable-recycler-view#162]
whenever I expand a parent item and want to expand another parent item the ```getAdapterPosition()``` method returns wrong position.
How can I get correct expanded parent position so I can access It's children?

**Comment by hrsalehi** [comment]
I worked on It a lot and tested many approaches but I couldn't solve the problem. here is my code

```java
@Override
    public void onBindParentViewHolder(ParentViewHolder parentViewHolder, final int position,final ParentListItem parentListItem) {

        subMenuParentHolder = (SubMenuParentHolder) parentViewHolder;
        final Menu menu = (Menu) parentListItem;
        subMenuParentHolder.bind(menu);
        subMenuParentHolder.tittleButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

               //this line checks if the clicked parent item has children. but the position is wrong when another parent expanded
               mainFragment.menuParentClicked(position);

                if (lastPosition == -1) {
                    expandParent(position);
                    lastPosition = position;
                }
                else if(lastPosition == position)
                {
                    collapseAllParents();
                    lastPosition = -1;
                }
                else
                {
                    collapseAllParents();
                    expandParent(position);
                    lastPosition = position;
                }
            }
        });
    }
```

Suppose the parent have 6 items and second child have 5 item. when I expand the second (position =1 ) item now the list have 11 items so when I click on the third (position = 2) parent instead of it's position I will get (position = 2 + 5).

**Comment by paul-turner** [comment]
Currently the viewholders do not have an idea of parent position, so getAdapterPosition is returning the position including both children and parents. Does that add up with what you are seeing?

Unfortunately the best solution right now is to store that information on your parent object yourself and pull it out from there. #157 is tracking the effort to improve this for the library

**Comment by paul-turner** [comment]
With #171 there is now a snapshot build that should let you access more information from the `ViewHolder`s:
- Added ParentViewHolder methods:
    - `getParentListItem()`
    - `getParentAdapterPosition()`
- Added ChildViewHolder methods:
    - `getChildListItem()`
    - `getParentAdapterPosition()`
    - `getChildAdapterPosition()`

This required changing the package location so bumped up the version to 3.0.0, which means this will probably be a snapshot for a bit as we get more features in for the library.
Instructions on how to get the snapshot are available in the `README` at https://github.com/bignerdranch/expandable-recycler-view/tree/dev

Let me know what you think.

**Comment by schelbin** [comment]
the version 3.0.0 is not functioning, just the 2.1.1 any other solution to this issue?
