### ISSUE TITLE
Cannot make Model implement ParentListItem

### ISSUE THREAD

**Issue by Rodrigo4R** [bignerdranch/expandable-recycler-view#163]
What would can i do if for some reason my model class cannot implement the ParentListItem interface? Is there any workaround?

**Comment by Clay24g** [comment]
I don't understand how it wouldn't be able to implement it. Please explain.

Otherwise, I suppose you could make another class, implement the interface, and have it contain an instance (object) of your parent model class, but I don't recommend that.

**Comment by paul-turner** [comment]
Yea, if you are using objects that are out of your control (from another library etc). You can have an object be a wrapper for that object, and have that wrapper implement the `ParentListItemInterface`.
