### ISSUE TITLE
Child onClickListener

### ISSUE THREAD

**Issue by Clay24g** [bignerdranch/expandable-recycler-view#164]
Hello, I apologize if this is obvious to everyone but me, but the ChildViewHolder class doesn't implement onClick.

I tried implementing the View.OnClickListener in both my own child holder class and also in the libraries source code (similar the parent view holder class). Neither seemed to work. The parent view holder click listener works just fine, though.

I just want to know how to add a listener to the child items, as I have everything else working great. 

If this feature could be added to the library, it would be great.

Thanks.

**Comment by Clay24g** [comment]
I implemented a workaround by giving the text element within the row a click listener. Since the text fills the entire row, this works just fine. However, it wouldn't be as useful if your child row has multiple elements, though I suppose you could set them all to the same listener. I'm new to Android but that sounds a little messy.

Here's some code if anyone was wondering:

```
public static class MyChildViewHolder extends ChildViewHolder implements View.OnClickListener
{
    TextView title;

    public MyChildViewHolder(View v) 
    {
        super(v);
        title = (TextView) v.findViewById(R.id.btn);
        title.setOnClickListener(this);
    }

    @Override
    public void onClick(View v)
    {
        Toast.makeText(context, title.getText(),
                Toast.LENGTH_SHORT).show();
    }
}
```

**Comment by paul-turner** [comment]
Instead of implementing the interface, I think you could make a set of anonymous inner classes that implement the onClickListener. Something like: 
```java
public static class MyChildViewHolder extends ChildViewHolder {
    TextView title;

    public MyChildViewHolder(View v) {
        super(v);
        title = (TextView) v.findViewById(R.id.btn);
        title.setOnClickListener(new View.onClickListener() {
            @Override
            public void onClick(View v) {
                        Toast.makeText(context, title.getText(),
                                Toast.LENGTH_SHORT).show();
            }
        });
    }

```

**Comment by Clay24g** [comment]
That is correct, it works like that. I just used the interface for readability instead of making it an inner class. I'm not sure if that will have any different effect than the solution you posted, but they both seem to work equally.

Thank you very much.

**Comment by lectricas** [comment]
@paul-turner why I need to add some View in order to get onClick event? What if I have no view at all or they are too small to click?

**Comment by paul-turner** [comment]
@lectricas if you have no view then nothing is being displayed to the user which means they have nothing to click. If you have something that is too small to click I would recommend having a container that is slightly larger so that the user has the ability to click on something.

Hopefully that helps!

**Comment by i-schuetz** [comment]
What would be a convenient way to get the model of the row in the click listener? The view holder doesn't know where the view is or anything. Maybe add the listener in `onBindChildViewHolder`?
