### ISSUE TITLE
How to get actual child view position?

### ISSUE THREAD

**Issue by aman007jham** [bignerdranch/expandable-recycler-view#165]
Like you check in expandableListView if you click on childItem that position i needed?

Can you guys tell me how i achieve that.

**Comment by paul-turner** [comment]
unfortunately we do not have good support for that in the library right now. You could store the position information in the childObject and go from there. #157 is tracking the effort to improve this.

**Comment by tomvakninorg7** [comment]
```
  @Override
    public void onBindChildViewHolder(TopicChildHolder childViewHolder, int position, Object childListItem) {
        final Topic child = (Topic) childListItem;
        childViewHolder.topicName.setText(child.getTopicTitle());
        childViewHolder.container.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                  // insert code here - there you have the current child
            }
        });

    }
```

**Comment by orafaaraujo** [comment]
Solution that @tomvakninorg7 described is not working for me on a complex list.
Some times the `childListItem` is not the one that i clicked!

**Comment by orafaaraujo** [comment]
@tomvakninorg7 my apologies, was not working because some of mine items does not have onClickListener and i war forgoting to set setOnClickListener(null).
I'm Sorry!

**Comment by paul-turner** [comment]
With #171 there is now a snapshot build that should let you access more information from the `ViewHolder`s:
- Added ParentViewHolder methods:
    - `getParentListItem()`
    - `getParentAdapterPosition()`
- Added ChildViewHolder methods:
    - `getChildListItem()`
    - `getParentAdapterPosition()`
    - `getChildAdapterPosition()`

This required changing the package location so bumped up the version to 3.0.0, which means this will probably be a snapshot for a bit as we get more features in for the library.
Instructions on how to get the snapshot are available in the `README` at https://github.com/bignerdranch/expandable-recycler-view/tree/dev

Let me know what you think.

**Comment by aman007jham** [comment]
Thanks @paul-turner for making such a nice library. I tried `getChildListItem()` & `getParentAdapterPosition()` its working like same ExpandableListView.

Now, I am trying to implement in your library **EndlessRecyclerOnScrollListener** but now i am facing the issue in adapter.notifyDataSetChanged().

I am not getting  why this method  not working. What do you think?

**Comment by dgreenhalgh** [comment]
@aman007jham, is the `notifyDataSetChanged()` you're referring to in your question `ExpandableRecyclerAdapter.notifyDataSetChanged()` or `RecyclerView.notifyDataSetChanged()`? 

We haven't yet provided an implementation for an overall `ExpandableRecyclerAdapter.notifyDataSetChanged()`, but in the mean time you should be able to use individual or ranged notify methods to achieve what you're looking for.

We're tracking that feature addition here: https://github.com/bignerdranch/expandable-recycler-view/issues/89
