### ISSUE TITLE
Notify method [SOLVED]

### ISSUE THREAD

**Issue by joek85** [bignerdranch/expandable-recycler-view#166]
Hey guys , i have been stuck with notifyChildItemRemoved wich it needs 2 arguments :parentposition and childposition , i tried to apply it from onBindParentViewHolder but the position is not what it needs.
I found out that all notify methods actually needs the parent and child index not their position inside the adapter so i came out with this solution , hope it helps you guys.

First you need to add a argument to the childitem like this:

```java
 private int mHeaderIndex;
    public ItemsAudio(int Headerindex) {
                mHeaderIndex = Headerindex;
    }
 public int getmHeaderIndex() {
        return mHeaderIndex;
    }
```
Then in your Adapter 

```java
public void onBindChildViewHolder(final ItemViewHolder ingredientViewHolder, final int position, final Object childListItem) {
        final ItemsAudio item = (ItemsAudio) childListItem;
final ParentListItem parentListItem = arrayList.get(item.getmHeaderIndex());
                        final List list = parentListItem.getChildItemList();
                        notifyChildItemRemoved(item.getmHeaderIndex(), list.indexOf(item));
              
}
```

```java
   private List<? extends ParentListItem> arrayList;

    public AudioAdapter(Context context1, @NonNull List<? extends ParentListItem> parentItemList) {
        super(parentItemList);
        context = context1;
        mInflator = LayoutInflater.from(context);
        arrayList = parentItemList;
    }
```

At least it worked for me , i may not know if this is the best solution but i tried my best to not hard code it.
hope this would help all who was struggling a bit to find out a solution like me , thanks for the author for this beautiful library and i would suggest to change `public void notifyChildItemRemoved(int parentPosition, int childPosition)` to `public void notifyChildItemRemoved(int parentIndex, int childIndex)`
BTW im sorry for this mess i am new to github and i couldnt figure out how to paste a code properly so excuse me.
Thank you , enjoy.

**Comment by paul-turner** [comment]
Cleaned up your code formatting a little bit, thanks for sharing! Very useful for users until I get around (hopefully soon) to giving a solution baked into the library.

**Comment by paul-turner** [comment]
Hi @joek85, with #171 there is now a snapshot build that should let you access more information from the `ViewHolder`s, which will help you not need to store extra position information in your objects:
- Added ParentViewHolder methods:
    - `getParentListItem()`
    - `getParentAdapterPosition()`
- Added ChildViewHolder methods:
    - `getChildListItem()`
    - `getParentAdapterPosition()`
    - `getChildAdapterPosition()`

This required changing the package location so bumped up the version to 3.0.0, which means this will probably be a snapshot for a bit as we get more features in for the library.
Instructions on how to get the snapshot are available in the `README` at https://github.com/bignerdranch/expandable-recycler-view/tree/dev

Let me know what you think.

**Comment by joek85** [comment]
Thank you @paul-turner,i will try it soon and give you my thoughts , thank you for your work
