### ISSUE TITLE
i am not arrow rotation animation.. 2.1.1 version

### ISSUE THREAD

**Issue by dlsdnd345** [bignerdranch/expandable-recycler-view#172]

**Comment by dgreenhalgh** [comment]
Hey @dlsdnd345, I just tried out our 2.1.1 and I'm not seeing any difference with respect to the arrow rotation animation. Could we have some more information on what you're seeing?

**Comment by paul-turner** [comment]
Seems description was edited out, mentioned going from 1.1.3 to 2.1.1

Please look at https://github.com/bignerdranch/expandable-recycler-view/blob/master/MIGRATION.md
and an example sample of the new way to do rotating at https://github.com/bignerdranch/expandable-recycler-view/blob/master/sampleapp/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/vertical/RecipeViewHolder.java
