### ISSUE TITLE
Is it possible to have a parent view holder in a parent view holder?

### ISSUE THREAD

**Issue by ThatKawaiiGuy** [bignerdranch/expandable-recycler-view#173]
Hello, I'm attempting to make a parent inside a parent view holder so I could have a expandable list inside another expandable list, but I'm not sure how to do it.

How would one do this?

Thank you.

**Comment by paul-turner** [comment]
Hi Ivan,
This is not supported as of now, might be something that can be supported in the later stages of the library with more work.
