### ISSUE TITLE
Make Child Lists use GridLayoutManager?

### ISSUE THREAD

**Issue by MattS8** [bignerdranch/expandable-recycler-view#174]
I'm trying to use the snapshot, and I followed the instructions exactly, yet I still get the error `Failed to resolve: com.bignerdranch.android:expandablerecyclerview:3.0.0-SNAPSHOT`

What's up??

**Comment by paul-turner** [comment]
@MattS8 Sorry for the delay in response, I thought I pushed the snapshot but had a typo in the word `SNAPHSOT`, it should be available now though per #175, I'm going to close this issue but would love if you can confirm/deny your ability to download in #175 

Thanks!
