### ISSUE TITLE
3.0.0-SNAPSHOT not available from sonas repo

### ISSUE THREAD

**Issue by eduplus** [bignerdranch/expandable-recycler-view#175]
Dev branch has some new changes, which I would like to test, but when I follow the instructions to add the snapshot to gradle, it is not found. When I go to see the snapshot repo using browser, I can only see 1.1.0-SNAPSHOT there.

**Comment by paul-turner** [comment]
I misspelled the word SNAPSHOT when publishing the other day :( 

Thank you for pointing it out! Pushed it out now and confirmed its there (hopefully I'm right this time), may take an hour or two to propagate through the servers.
