### ISSUE TITLE
Custom layouts(with your own views + clicklisteners for them) for Parent and Child Holders

### ISSUE THREAD

**Issue by rohanmahale** [bignerdranch/expandable-recycler-view#177]
Is it possible to implement this?

I need a checkbox in my parentVH as well as checkboxes in the child VHs. Checking on the parent one should automatically toggle the values on the corresponding children. Also, is it possible to maintain the states of these checked items when we expand/collapse + scroll ?

**Comment by paul-turner** [comment]
@rohanmahale Yes of course! The samples should give you a good starting point to figuring things out, we use custom click listeners on an view within the row, easily replaced by a checkbox though.
As far as maintaining the state, you could do so in your viewholders and adapter just like with any other recycler view.

Hope the samples help in getting you started, let me know if I misunderstood your question.

**Comment by rohanmahale** [comment]
Yup. I've put in my own layouts, i.e checkboxes in the parent and children, now I need to work on maintaining the states.

**Comment by rohanmahale** [comment]
Hey @paul-turner . I'm having issues while trying to maintain states. Also, scrolling is calling issues . Could you help me out with what changes need to be made where? Also I require the OnCheckChangedListener to function correctly.

**Comment by rohanmahale** [comment]
This seems to be working for the parent views 

`    @Override
    public void onBindParentViewHolder(final RecipeViewHolder recipeViewHolder, final int position, final ParentListItem parentListItem) {
        //Recipe recipe = (Recipe) parentListItem;
        recipeViewHolder.mRecipeTextView.setText(((Recipe) getParentItemList().get(position)).getName());
        recipeViewHolder.mCheckBox.setOnCheckedChangeListener(null);
        recipeViewHolder.mCheckBox.setChecked(((Recipe) getParentItemList().get(position)).ismSolved());
        recipeViewHolder.mCheckBox.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                //set your object's last status
                ((Recipe) getParentItemList().get(position)).setmSolved(isChecked);
                notifyParentItemChanged(position);
                recipeViewHolder.mCheckBox.setSelected(isChecked);
            }
        });
    }`

**Comment by rohanmahale** [comment]
Is it possible to get info about the parent(category) when we click on a child(sub-category) in the 
OnBindChildViewHolder ??
The parameters are ChildVH ,  position and the ChildListItem Object. In this case is position, the position of the parent??

**Comment by rohanmahale** [comment]
Figured it out.
