### ISSUE TITLE
Identify Parent from a Child's perspective.

### ISSUE THREAD

**Issue by rohanmahale** [bignerdranch/expandable-recycler-view#178]
Can we identify/retrieve the parent view and the data associated with it from a child view? If so, how is it done?

**Comment by paul-turner** [comment]
@rohanmahale In the `dev` branch we have the ability to get the index information of the parent and child from a child view. From there you should be able to pull data associated from your data constructs. Give it a shot, instructions on how to get the SNAPSHOT build are in the readme: https://github.com/bignerdranch/expandable-recycler-view/tree/dev

**Comment by rohanmahale** [comment]
Hi @paul-turner . It seems to be working quite well. I'm still testing. 

Another issue, I'm facing currently is with the notify... methods. In my case my parents and children all have checkboxes. Selecting a parent triggers selection on all children. Selecting all children triggers selection of the parent(sort of a tree structure).  I've tried using the notifyParentItemChanged since it triggers listeners on the children, however I get index out of bounds exceptions eventually, when i keep selecting/deselecting.  With notifyDataSetChanged, I do not have this problem. 

Any idea why this might be happening? (I hope I've explained it clearly - Do let me know if I have not)

**Comment by paul-turner** [comment]
Hmmm, off the top of my head:
Either we have a bug inside the `notifyParentItemChanged` method or the index being passed in to the method is incorrect in some way. Would start by double checking the right parent index is given (which it should be if you are using those new adapter methods). Or there might be a bug within `getParentAdapterPosition()`

Would need some more information to try and track those down, which indices it seems more likely to crash on, size of the list, any other peculiar information etc.
