### ISSUE TITLE
Version Error

### ISSUE THREAD

**Issue by Hemant0601** [bignerdranch/expandable-recycler-view#179]
Error:Failed to resolve: com.android.support:recyclerview-v7:23.2.0
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:/Users/hemantkumar/Documents/Orahi/orahiandroid/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by paul-turner** [comment]
@Hemant0601 looks like you need to download the new 23.2.0 support libraries in your Android SDK. See http://developer.android.com/tools/support-library/setup.html for details where you would install/update the support library.

**Comment by Hemant0601** [comment]
Thanks
