### ISSUE TITLE
Empty RecyclerView (onBind methods not called)

### ISSUE THREAD

**Issue by atordoadao** [bignerdranch/expandable-recycler-view#180]
The activity RecyclerView is appears like its empty, but programatically its not, i've been having this problem since 2 days ago, none of 2 parent items and its child is showing.

method of activity:
```java
private void refreshLista() {
        CategoriaDAO cDAO = new CategoriaDAO(this);
        SubCategoriaDAO sDAO = new SubCategoriaDAO(this);
        List<Categoria> cList = cDAO.getLista(0);
        for (Categoria c : cList) {
            List<SubCategoria> sList = sDAO.getLista(c.getId());
            c.setChildList(sList);
        }
        SubcategoriaExpandableAdapter adapter = new SubcategoriaExpandableAdapter(this, cList);
        mRecyclerView.setAdapter(adapter);
    }
```

expandable adapter 
```java
public class SubcategoriaExpandableAdapter extends ExpandableRecyclerAdapter<CategoriaViewHolder,SubcategoriaViewHolder> {
    private LayoutInflater mInflater;


    public SubcategoriaExpandableAdapter(Context context, @NonNull List<? extends ParentListItem> categoriaList){
        super(categoriaList);
        mInflater = LayoutInflater.from(context);
    }

    @Override
    public SubcategoriaViewHolder onCreateChildViewHolder(ViewGroup childViewGroup) {
        View view = mInflater.inflate(R.layout.subcategoria_row, childViewGroup, false);
        return new SubcategoriaViewHolder(view);
    }

    @Override
    public CategoriaViewHolder onCreateParentViewHolder(ViewGroup parentViewGroup) {
        View view = mInflater.inflate(R.layout.categoria_row, parentViewGroup, false);
        return new CategoriaViewHolder(view);
    }

    @Override
    public void onBindParentViewHolder(CategoriaViewHolder parentViewHolder, int position, ParentListItem parentListItem) {
        Categoria categoria = (Categoria) parentListItem;
        parentViewHolder.bind(categoria);
     }

    @Override
    public void onBindChildViewHolder(SubcategoriaViewHolder childViewHolder, int position, Object childListItem) {
        SubCategoria subCategoria = (SubCategoria) childListItem;
        childViewHolder.bind(subCategoria);
    }


}
```

parent viewholder
```java
public class CategoriaViewHolder extends ParentViewHolder {
    public TextView mCategoria;

    public CategoriaViewHolder(View view){
        super(view);
        mCategoria = (TextView) view.findViewById(R.id.tvCat);
    }

    public void bind(Categoria categoria){
        mCategoria.setText(categoria.getNome());
    }

}
```

child viewholder

```java
public class SubcategoriaViewHolder extends ChildViewHolder {

    public TextView mSubcategoria;
    public ImageButton mOpcoes;


    public SubcategoriaViewHolder(View item) {
        super(item);

        mSubcategoria = (TextView) item.findViewById(R.id.tvSubCat);
        mOpcoes = (ImageButton) item.findViewById(R.id.opcsubcat);
    }

    public void bind(SubCategoria subCategoria) {
        mSubcategoria.setText(subCategoria.getNome());
    }


}
```

activity xml

```xml
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recySub"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="#cccccc"/>

</FrameLayout>
```

Thank you for your help

**Comment by paul-turner** [comment]
Just a quick guess here, I think this is caused by our upgrade to support library 23.2 and having `wrap_content` in the height of the `RecyclerView`.  Change it to match_parent and let me know if that works!

**Comment by atordoadao** [comment]
Same as before, it paints the whole screen with the background but no items.

**Comment by paul-turner** [comment]
Shucks, on more guess:
What about the layout of your list items, do those have wrap content in their height?

**Comment by atordoadao** [comment]
Yep, both of them.

parent-row.xml

`<?xml version="1.0" encoding="utf-8"?>
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/some_card_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="8dp"
        android:layout_marginRight="8dp"
        android:layout_marginTop="8dp">
            <TextView
                android:id="@+id/tvCat"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_margin="8dp"
                android:text="Large Text"
                android:textAppearance="?android:attr/textAppearanceMedium" />


    </LinearLayout>`


child-row.xml

`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent" android:layout_height="match_parent">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textAppearance="?android:attr/textAppearanceMedium"
        android:text="Medium Text"
        android:id="@+id/tvSubCat"
        android:layout_marginLeft="37dp"
        android:layout_marginStart="37dp"
        android:layout_marginBottom="8dp"
        android:layout_marginTop="8dp" />

    <ImageButton
        android:contentDescription="Opções"
        android:src="@drawable/dots_vertical"
        android:background="@android:color/transparent"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/opcsubcat"
        android:layout_alignParentRight="true"
        android:layout_alignParentEnd="true"
        android:layout_marginRight="8dp"
        android:layout_alignBottom="@+id/tvSubCat" />

</RelativeLayout>`

**Comment by paul-turner** [comment]
Hmmm nothing stands out for me looking at the code and xml. Here are a set of questions that may lead to something:
Is there anything outside that code may have changed? when you set a breakpoint in `refreshLista` does `cList` have the items inside it as you expect? Do the items have valid text that would be visible once the bind happens? Does the recycler view have a `LayoutManager` set?

**Comment by atordoadao** [comment]
Q1: When you set a breakpoint in refreshLista does cList have the items inside it as you expect? 
A1: cList have the items inside like I expect.
Q2: Do the items have valid text that would be visible once the bind happens? 
A2: Yes, but when I set a breakpoint on any onBind methods of ExpandableAdapter they are not called, I guess that is the problem.

**Comment by egor-n** [comment]
@atordoadao what about the `LayoutManager`?

**Comment by atordoadao** [comment]
@egor-n the RecyclerView doesn't have a LayoutManager set

**Comment by paul-turner** [comment]
After setting one does that fix the problem?

**Comment by atordoadao** [comment]
@paul-turner I don't know how to do this, do you know a tutorial to be followed?

**Comment by paul-turner** [comment]
See the first section "Creating Lists" http://developer.android.com/training/material/lists-cards.html

Also can see in our sample: 
https://github.com/bignerdranch/expandable-recycler-view/blob/master/sampleapp/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/vertical/VerticalLinearRecyclerViewSampleActivity.java#L78

**Comment by XilonTrade** [comment]
Hi, I know it is an old issue, but I had the same issue as atordoadao and implementing LayoutManager solved the problem. I guess maybe your tutorials are missing this part, as for some people it may not be that obvious. Thanks!

**Comment by paul-turner** [comment]
@XilonTrade Thank you I'll look into adding a note into our documentation mentioning that bit!

**Comment by mwshubham** [comment]
Thanks setting layout manger works for me
