### ISSUE TITLE
Add a card view frame around the recycler view

### ISSUE THREAD

**Issue by MZapatae** [bignerdranch/expandable-recycler-view#181]
It´s possible add a frame simulate a material card view around every parent list and his children?
To improve the UI?

pd: sorry for my english, my native language is Spanish.
pd2: Great job with this library, is awesome.

**Comment by paul-turner** [comment]
@MZapatae It should be possible. Would require some custom view logic of when to show the bottom portion of the card (ie show it on the parent when items are collapsed, show it on the last child when the parent is expanded).
