### ISSUE TITLE
Restore state on rotate issues

### ISSUE THREAD

**Issue by yitz-grocerkey** [bignerdranch/expandable-recycler-view#188]
First off, thanks for the great library and support. It looks great and works perfectly (other than this). I'm having an issue on restoring state on rotation. Just doesnt work. Here is the relevant code:

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setRetainInstance(true);
    }
    
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        _recyclerView = (RecyclerView) inflater.inflate(R.layout.fragment_categories, container, false);

        _recyclerView.setLayoutManager(new LinearLayoutManager(getActivity()));
        _categoriesAdapter = new CategoriesAdapter(getActivity(), _categoryList);
        _categoriesAdapter.onRestoreInstanceState(savedInstanceState);
        _recyclerView.setAdapter(_categoriesAdapter);

        return _recyclerView;
    }

    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        _categoriesAdapter.onSaveInstanceState(outState);
    }
I have already spent hours trying to figure this out with no success. if anyone has any ideas please reply.

**Comment by paul-turner** [comment]
@yitz-grocerkey Interesting, your code looks to be set up correctly here. Could you expand on what you are seeing as a bug? Are none of the expanded items are staying expanded after rotation?

Is it possible that the sample app is showing this same non working behaviour for you (would help so I can debug through the code)?

**Comment by yitz-grocerkey** [comment]
@paul-turner, thanks for replying. 

Yeah, I guess I could have been clearer about what the issue was exactly. Basically the expanded parent stays collapsed on rotation. I tried the sample app and it seems to be working perfectly. So unfortunately not much help there. 

The behavior I programmed into the adapter to do is as follows:
1. If a parent is expanded it collapses when another parent expands.
2. The parent view has a different look in its expanded state (background color, text size, etc).
3. Clicking a collapsed parent expands it.
4. Clicking an expanded parent (or a child) transitions to another fragment.

Please ask any followup questions. I'm very grateful for any help.

Related code:

```
public class CategoriesAdapter extends ExpandableRecyclerAdapter <CategoriesAdapter.CategoryViewHolder, CategoriesAdapter.SubCategoryViewHolder>{

    // etc
    
    // used to keep track of currently expanded parent
    private Integer _currentExpandedCategoryIndex = null;

    // etc
    public class CategoryViewHolder extends ParentViewHolder {
        // etc

        // called in onBindParentViewHolder
        public void bind(final Category category) {
            _category = category;
            if (isExpanded()) {
                // set expanded view attributes
            } else {
                // set collapsed view attributes
            }

            Row.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    if (!isExpanded()) {
                            expandView();
                    } else {
                        // notify fragment that need to transition to another fragment
                        _recyclerViewAdapterCallbacks.onItemClick(_category.getName());
                    }
                }
            });
        }
    
        @Override
        public void onExpansionToggled(boolean expanded) {
            if (_currentExpandedCategoryIndex != null) {
                collapseParent(_currentExpandedCategoryIndex);
                notifyParentItemChanged(_currentExpandedCategoryIndex);
            }
            _currentExpandedCategoryIndex = getParentItemList().indexOf(_category);
            super.onExpansionToggled(expanded);
            notifyParentItemChanged(_currentExpandedCategoryIndex);
        }

        @Override
        public boolean shouldItemViewClickToggleExpansion() {
            return false;
        }
    }
}
```

**Comment by paul-turner** [comment]
Hmm everything still looks correct. 
Would need to take a look at the state while running to better see what is going wrong. I would take a look at what it is doing through https://github.com/bignerdranch/expandable-recycler-view/blob/master/expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/Adapter/ExpandableRecyclerAdapter.java#L1113 and see if it is missing your row being expanded, if not then something is going wrong on the restore side of things. Which would be here:
https://github.com/bignerdranch/expandable-recycler-view/blob/master/expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/Adapter/ExpandableRecyclerAdapter.java#L457
