### ISSUE TITLE
How to delete all elements from list?

### ISSUE THREAD

**Issue by JustTrust** [bignerdranch/expandable-recycler-view#189]
Please tell me, how to delete all elements from list?

**Comment by oguzhandongul** [comment]
I found a way to remove any element of the list.

list.remove(index);
mAdapter = new MyAdapter(this, list);
recyclerView.swapAdapter(mAdapter,false);

First, remove your items from list,
Initialise your adapter again.
And finally swap your new initialised adapter with old one.

Otherwise removing and calling notifyDataSetChanged() is not working at all.

**Comment by baka-kaba** [comment]
If you look at [the tutorial page](http://bignerdranch.github.io/expandable-recycler-view/), at the bottom it says

> During the life of the RecyclerView items may be added and removed from the list. **Please note that the traditional notifyDataSetChanged() of RecyclerView.Adapter does not work as intended.**

> Instead Expandable RecyclerView provides a set of notify methods with the ability to inform the adapter of changes to the list of ParentListItems.

```
// Parent Changes
notifyParentItemInserted(int parentPosition)
notifyParentItemRemoved(int parentPosition)
notifyParentItemChanged(int parentPosition)
notifyParentItemRangeInserted(int parentPositionStart, int itemCount)
    
// Child Changes
notifyChildItemInserted(int parentPosition, int childPosition)
notifyChildItemRemoved(int parentPosition, int childPosition)
notifyChildItemChanged(int parentPosition, int childPosition)
```

So you need to use those methods. If you want to delete everything, you can remove them from the list (use `getParentItemList()` if you don't have a reference) and then do `notifyParentItemRangeRemoved(0, list.size())` . That will mark all the elements as removed - you need to make sure the list isn't already empty though, or you'll get an IndexOutOfBoundsException (it tries to access element 0 of the empty backing array)

**Comment by JustTrust** [comment]
Thanks!

**Comment by paul-turner** [comment]
Thank you @baka-kaba for your support!
