### ISSUE TITLE
Usage with loader

### ISSUE THREAD

**Issue by PRosenb** [bignerdranch/expandable-recycler-view#191]
I use the expandable recycler view in a fragment and load the data with a loader.
This means, that the data is not available in the `onCreate()` or `onCreateView()` methods but in the method `onLoadFinished()`.
The problem is, that the adapter forces me to set the data when calling its constructor and does not allow to set it later. Due to that fact, I cannot use the method `onRestoreInstanceState()` because when `onCreate()`/`onCreateView()` is called, the adapter is not yet created.

It would therefore be great to have a separate method to supply the data and also store the `savedInstanceState` in the adapter until the data is set.

**Comment by paul-turner** [comment]
@PRosenb Interesting problem. I would recommend you store the savedinstancestate until you can use it in the `onLoadFinished` I worry that if the library does so it'll lead to a little bit of bloat on what the library handles. As far as supplying the data I agree that not having better setters of data is holding you back here. Once we get around to implementing `notifyDataSetChanged()` we should be able to set the data entirely and call for a refresh, for now it seems you might be better off setting up a new adapter in your `onLoadFinished()` restoring the state, and passing in the adapter with [swapAdapter()](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.html#swapAdapter(android.support.v7.widget.RecyclerView.Adapter, boolean))

Did I understand your issue correctly, it seems there is nothing entirely blocking your functionality but instead things we can do to make your life a little easier (ala having a working `notifyDataSetChanged()` method?)?

**Comment by PRosenb** [comment]
Hi Paul, thanks for your reply.
To me it looks like a good design to keep the adapter and supply it with the savedInstanceBundle in the appropriate callback methods of the fragment. That's also done this way in the Loader description:
[Loaders](http://developer.android.com/guide/components/loaders.html)

Yes I agree, adding the ability to set the data on an existing loader would improve it much. When the savedInstanceBundle is set before in the callback methods of the fragment, I think it should be applied when the data is then set later on.

This issue doesn't block me, I will do the workaround you suggested.

**Comment by paul-turner** [comment]
Good luck with the workaround.

Seems like there is no direct action from this right now (apart from `notifyDatasetChanged` which is being tracked in #89 ) I will close this but feel free to comment again if something comes up directly related to this.
