### ISSUE TITLE
Hard time implementing Filter on this adapter

### ISSUE THREAD

**Issue by XilonTrade** [bignerdranch/expandable-recycler-view#193]
Hi, first of all, thanks for providing this amazing library. I've been implementing you ExpendableRecyclerAdapter with success, but I've been caught in a huge struggle: I'm finding really dificult to implement a filterable on this adapter. On regular adapters, i could implement it easily mainly because i had permission to edit the main list. In your implementation, a can only edit the list through these methods: 
// Parent Changes
notifyParentItemInserted(int parentPosition)
notifyParentItemRemoved(int parentPosition)
notifyParentItemChanged(int parentPosition)
notifyParentItemRangeInserted(int parentPositionStart, int itemCount)
    
// Child Changes
notifyChildItemInserted(int parentPosition, int childPosition)
notifyChildItemRemoved(int parentPosition, int childPosition)
notifyChildItemChanged(int parentPosition, int childPosition)

And its complicated, because i cannot set the list directly, i can only add or remove some items through those methods. Do you have any idea or suggestions on how to implement a filter where, on each letter i input on a search field it filters our list? I could do this easily on a common adapter because i could set directly our list.

Thanks!

**Comment by paul-turner** [comment]
Hi @XilonTrade 
You are right, there is one missing piece to make your life simpler and that would be a general `notifyDataSetChanged()` method that could use stable Id's to rebuild the expanded state. That effort is being tracked in #89.

As a hack while that feature waits to be implemented, I can think of one thing that might make your life easier:

1. Keep track of the last expanded state in your model object
2. When you need to make a filter change create a new adapter with your filtered items
3. These filtered items should return the last expanded state in `isInitiallyExpanded` as a fake way to maintain expanded state
4. Swap the adapter in your recyclerview. (or remove all the items and say `notifyParentItemRangeRemoved`, then add the filtered items with `notifyParentItemRangeInserted`)

Unfortunately I'm not sure which approach (swapping adapters vs notify removed/inserted) will give you the better result in terms of animations/looks.

**Comment by XilonTrade** [comment]
Hi Paul, thanks for your response. I'll try one of your suggestions while this feature is not implemented.
