### ISSUE TITLE
Not working with Recycler and Support Design 23.3

### ISSUE THREAD

**Issue by shinayser** [bignerdranch/expandable-recycler-view#194]
Hey!

The recycler is not working anymore when using the new support library 23.3:

    compile 'com.android.support:design:23.3.0'
    compile 'com.android.support:recyclerview-v7:23.3.0'
    compile 'com.bignerdranch.android:expandablerecyclerview:2.1.1'

But using this it works:

    compile 'com.android.support:design:23.2.0'
    compile 'com.android.support:recyclerview-v7:23.2.0'
    compile 'com.bignerdranch.android:expandablerecyclerview:2.1.1'

The problem is that when using 23.3 the recycler shows nothing. It gets entirely blank.

I don't know what is causing this.

Best regards and thanks for such nice library!

**Comment by paul-turner** [comment]
Hi @shinayser I haven't been able to reproduce this with our samples, any chance you could test it out there and see if you get the same results? otherwise maybe it's specific with your project.

**Comment by shinayser** [comment]
I found a way to fix it on my case.

My recyclerview was set to "wrap_content" and working fine on 23.2.

After updating to 23.3 (and the new 23.4) the recycler was not wraping its content. I saw it because my recyelr had a padding of 2dp and when turning the develop option "Show layout bounds" (on the Developer  Options on my Android device) I could see the recycler with its 2dp padding (a small 4dp height line).

So, this is what I've done: I changed the recyclerview height from "wrap_content" to 2000dp (Any large number, 1024 probably will be more than enough).

Thanks again for such nice library.

**Comment by dgreenhalgh** [comment]
Hey @shinayser, you may also want to try setting your RecyclerView's layout height to `match_parent`. Using an arbitrarily large size like 2000dp may put you at risk for not seeing all of the content in your RecyclerView on the screen.

Thanks for the kind words!
