### ISSUE TITLE
Question about method expandParen (int index)

### ISSUE THREAD

**Issue by ALEX-YxTY** [bignerdranch/expandable-recycler-view#195]
Hi,First of all, thank you for this library. It helps a lot.
But now i hava a problem.  After i swap the adapter of my recycleView because the parentItemList has totally changed, i use expandParent (index) to make some parentItem expanded. Then the exception came out.  But when i post this method 500 millisecond delayed, it works!
I don't know why……

**Comment by paul-turner** [comment]
Hi there,
Do you have a stack trace of the exception?
It is likely that we are trying to get some sort of item from the adapter before the RecyclerView has finished it's layout from the new cursor, but would need to see the exception to be more sure.
