### ISSUE TITLE
ParentView click

### ISSUE THREAD

**Issue by toSilence** [bignerdranch/expandable-recycler-view#201]
Hi,

unfortunately I found no way to detect if a parent item is clicked --> I want to change the background color.
But the events are not triggered.

Any help appreciated

**Comment by paul-turner** [comment]
@toSilence The sample apps in the repo should give you what you need as far as setting up your own custom click listeners. [HorizontalParentViewHolder](https://github.com/bignerdranch/expandable-recycler-view/blob/master/sampleapp/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/horizontal/HorizontalParentViewHolder.java) or [RecipeViewHolder](https://github.com/bignerdranch/expandable-recycler-view/blob/master/sampleapp/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/vertical/RecipeViewHolder.java) are good starting spots.
