### ISSUE TITLE
How can I use this library but use other view types as well

### ISSUE THREAD

**Issue by Sandrichka22** [bignerdranch/expandable-recycler-view#213]
I have a need to display expandable items in my RecyclerView, but the problem that I am having is that I already have 3 different view types in my current implementation. From the 3, 2 of the view types should be items that provide the expandable capability (will be parent items). My question is, can I use this library to provide the functionality or there is no easy way of implementing this. Any advice would be appreciated. Thanks!

**Comment by AdamMillerAsu** [comment]
I think in it's current version this is not possible. If you dig around in the code a bit you'll see that "int viewtype" in onCreateViewHolder(ViewGroup viewGroup, int viewType) is being used to determine if the view is a parentview or a childview. 

In many multi-view lists the viewType is used to determine the layout to select. You'll need to do some custom coding in your adapter to get this to work.

**Comment by pasha656** [comment]
https://github.com/bignerdranch/expandable-recycler-view/issues/108

**Comment by Sandrichka22** [comment]
Thank you. I looked into the issues a bit deeper than just reading the headlines, and I also came across the discussion. I think I will go with something like that as a temporary solution, but I am looking forward to see this implemented in some next release of this library because I like it very much.

**Comment by Sandrichka22** [comment]
Just realized that if I want to make a distinction between two Parent items, like I do, I can't call the super.getItemViewType (because this method will tell me only if the item is a parent item, but not what type of parent item) so the only way I can accomplish what I want is to have the instance of mItems and make the disctinction myslef. Is this available? Or can it be available?

**Comment by Sandrichka22** [comment]
OK, I implemented the getItemViewType method in my adapter where I make the distinction myself, whether the item is a parent item or a child item. I do exactly the same like the getItemViewType method from the library, because the getListItem(position) is protected and I can call it in my implementation. 
The trouble that I am facing right now is that when I determine that some item is a parent item, I want to be able to make a distinction between 3 other item types from an information than I get from the object of the list that I set to the adapter. And because this method gets called for child items as well, because child items are inserted into the list, I do not have the correct position of the item in the list that I provide as data to the adapter and I get indexOutOfBounds exception. (I hope I explained the problem so it is understandable). 

So my question right now is, how can I get this position so I can properly query for the object of that position, and then correctly return the item type.

**Comment by AdamMillerAsu** [comment]
>So my question right now is, how can I get this position so I can properly query for the object of that position, and then correctly return the item type.

@Sandrichka22 I think they added some functions that can get child and parent positions respectively in one of their dev builds. There is another question on issues page where they discuss this. Does this look like what you're looking for?


https://github.com/bignerdranch/expandable-recycler-view/issues/192
"Added ParentViewHolder methods:
getParentListItem()
getParentAdapterPosition()
Added ChildViewHolder methods:
getChildListItem()
getParentAdapterPosition()
getChildAdapterPosition()"

**Comment by Sandrichka22** [comment]
I managed to get the correct position by calling myDataList.indexOf(((ParentWrapper) listItem).getParentListItem()), so now I can correctly query the list that I pass to the adapter (myDataList).

**Comment by paul-turner** [comment]
Hi @Sandrichka22,
Sorry for the delay in response, thank you @AdamMillerAsu and @pasha656 for jumping in with some help. It seems like you have a workaround for now, any other problems you are running into?

I do have plans to work on #108 (also helps that we have some PR's to pull implementation details from), but can't give any insight as to when I'll have the time required.

**Comment by paul-turner** [comment]
With PR #234 we now should have better support for multiple views. I would love feedback before we make a release! Please leave feedback in the original issue tracking this feature #108 

You can see the 3.0.0 code [here](https://github.com/bignerdranch/expandable-recycler-view/tree/dev-3.0.0)

The [recipe sample](https://github.com/bignerdranch/expandable-recycler-view/blob/dev-3.0.0/sampleapp/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/vertical/RecipeAdapter.java) shows a quick example of using multiple view types

To use the snapshot you will need to add the following to your app's `build.gradle`:

```
compile 'com.bignerdranch.android:expandablerecyclerview:3.0.0-SNAPSHOT'
```

You will also need to add Sonatype's snapshots to your repositories closure in the root `build.gradle`:
 ```gradle
 allprojects {
     repositories {
         maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
     }
 }
 ```

Good luck!
