### ISSUE TITLE
With Fragment 

### ISSUE THREAD

**Issue by wnasaindika** [bignerdranch/expandable-recycler-view#214]
In my case, it is completely overwrite all recycle-views in fragment.For example, if you are trying to use recycle-view in fragment and if it display correctly and it will be display one element after using this lib.it will affect to all recycle views
 Not sure why ? 
looking forward to contribute something for this amazing library

**Comment by lion4ik** [comment]
I have the same problem. Did you solve it ?

**Comment by wnasaindika** [comment]
Sorrry mate, i used inject card view into recycle -view

**Comment by paul-turner** [comment]
@wnasaindika  @lion4ik 
Whether this library is used in a fragment or not shouldn't be affecting the display of number of items. Both of our samples use fragments and display multiple items, by any chance are you overriding `getItemCount()` in your adapter?

**Comment by wnasaindika** [comment]
Hi Paul @paul-turner 
Thanks for the reply. 
I just called the library and it affected to other views on my app before I use it. For example, I had recycle view in fragment and it worked fine (Yes it had its own custom adapters ).Then I compile this library without using it on any view (Gradle compile)..eventually, the recycle views show me one item.I am not sure why this happen...

**Comment by paul-turner** [comment]
There has to be more to it, this library will have no effect if all you are doing is compiling it into your APK. There is no byte code weaving or anything hidden, just java classes that you have to implement. If you are not using it on any view, then it will not do anything.

**Comment by wnasaindika** [comment]
I am 100% sure mate (I just applied your lib again to confirm)..I am not sure why it happening..from my understanding it could be class overriding..it could be some fundamental error on operating system

**Comment by wnasaindika** [comment]
There is one main Activity and fragments. then there is an adapter extends RecyclerView.Adapter...The adapter will apply inside the fragment..That's my implementation..

**Comment by paul-turner** [comment]
What version of the support library are you using? might be that the library is bumping up your version and bringing out something wrong with your code. Anyways, can't guess at what is wrong without seeing code to figure out the actual problem, probably just something wrong in your adapter implementation if you are really using 0 of the expandable-recycler-view code and just adding it to gradle.

**Comment by ardock** [comment]
Fix rows height after updating recyclerView to version 23.2.1:
http://android-developers.blogspot.com.es/2016/02/android-support-library-232.html
http://stackoverflow.com/a/35747824/1009132

**Comment by paul-turner** [comment]
Yep that is likely the cause, thank you @ardock!
@wnasaindika If it still happens after changing your rows to `wrap_content` let me know.
