### ISSUE TITLE
Expending slow

### ISSUE THREAD

**Issue by amansingh005** [bignerdranch/expandable-recycler-view#217]
When I'm try to load data its loading very slow. 
```java
    public void getAllData(List<MenuAllItemGetSet> body) {

        for (Integer position = 0; position < body.size(); position++) {
            List<MenuSubItem> menuSubItemList = new ArrayList<>();
            List<Subcategory> menusubcat = body.get(position).getSubcategory();


            for (Integer subpos = 0; subpos < menusubcat.size(); subpos++) {
                List<Item> itemList;// = new Subcategory().getItem();
                itemList = menusubcat.get(subpos).getItem();
                List<Item> strings = new ArrayList<>();
                for (Integer itempos = 0; itempos < itemList.size(); itempos++) {
                    strings.add(itemList.get(itempos));
                }
                menuSubItemList.add(new MenuSubItem(menusubcat.get(subpos).getName(), strings));
            }
            menus.add(new MyMenu(body.get(position).getName(), menuSubItemList));
        }


        menuRecyclerAdapter = new MenuRecyclerAdapter(menus, getActivity());
        menuRecyclerAdapter.setExpandCollapseListener(new ExpandableRecyclerAdapter.ExpandCollapseListener() {
            @Override
            public void onListItemExpanded(int position) {
                menuRecyclerAdapter.expandParent(position);
                if (x != -1 && x != position)
                    menuRecyclerAdapter.collapseParent(x);
                Log.e(TAG, "onListItemExpanded: "+x +"  "+position);
                x = position;
            }

            @Override
            public void onListItemCollapsed(int position) {

            }
        });
        menuRecycleview.setAdapter(menuRecyclerAdapter);
    }
```
how to get resolved from this???

**Comment by XxGoliathusxX** [comment]
You have 3 nested for-loops. What did you think would happen?
Lets say the body has 10 items, the menusubcat and the itemlist too.
Then you already have 10*10*10 = 1000 for-loop-calls.

What do you want to load?

**Comment by paul-turner** [comment]
@amansingh005 Would probably need a little more information that you'd have to get from profiling your application. [Traceview](https://developer.android.com/studio/profile/traceview.html) might be a good tool for you to track down where your code (or our library code!) might be taking the most time. 

At a glance, depending on the size of your model data, it might indeed be the nested for-loops that is causing the slowdown.

**Comment by amansingh005** [comment]
@XxGoliathusxX you are right but my data is like that only... But that loop will call at once, only listener will call every-time but its taking time to load. Any #Idea how to get out from this problem?

**Comment by paul-turner** [comment]
Looks like you might be calling expand unnecessarily? in your `ExpandCollapseListener` you call `menuRecyclerAdapter.expandParent(position);` but it should already be expanded if you received this callback.
