### ISSUE TITLE
different item decoration and background color for parent item & child item individually

### ISSUE THREAD

**Issue by vipulasri** [bignerdranch/expandable-recycler-view#222]
I want to have different item decoration and background color for parent item & child item individually. is it possible in this library version?

**Comment by paul-turner** [comment]
Possible but maybe not very straightforward, would have to do something like this:
```
@Override
void onDraw (Canvas c, RecyclerView parent, RecyclerView.State state) {
    int position = parent.getChildAdapterPosition(view);
    if (parent.getAdapter().getItemViewType() == 0) {
        // is parent, draw parent colors
    } else {
        // is child, draw parent colors
    }
}
```

Not the best since it relies on some internal knowledge that 0 == parent and 1 == child type, but could at least get you started on the right path. Might be different once multiple view type support comes out.
