### ISSUE TITLE
How to make  part of the list of children did not collapse?

### ISSUE THREAD

**Issue by ulx** [bignerdranch/expandable-recycler-view#224]
How to make  part of the list of children did not collapse?

-parent (up)
--child1
--child2
to 
-parent (down)
--child1
--child2
--child3
--child4

**Comment by paul-turner** [comment]
Hmm interesting @ulx, currently that is not possible with the library. Best I can think of is to fake this behaviour by having the parent view holder look like Parent + child1 + child 2 no matter the expand or collapse state.
