### ISSUE TITLE
Not smooth expanding in Marshmallow 6.0.1

### ISSUE THREAD

**Issue by hcm-matineeidol** [bignerdranch/expandable-recycler-view#225]
When expanding an item in Android version 6.0.1. The expansion is not smooth or laggy.

Tested in Samsung Note 5.

**Comment by paul-turner** [comment]
Hi @hcm-matineeidol,
Any chance you can give more details with your implementation? How big is the dataset, what are you doing on expansion etc?

Even better would be some profiling of what you are seeing using [systrace](https://developer.android.com/studio/profile/systrace.html) would be perfect to see where we might be overloading the main thread.

**Comment by paul-turner** [comment]
Going to close this until more details are given
