### ISSUE TITLE
Is it possible to have static section Header?

### ISSUE THREAD

**Issue by AmirHadifar** [bignerdranch/expandable-recycler-view#230]
Hi , I want to know is it possible to have static section header for group of parent something like following:

- header1
  - expandable group1
    - child1
    - child2
 - expandable group2
   - child1
- header2
  - expandable group3
  - expandable group4

**Comment by paul-turner** [comment]
Hi @AmirHadifar 

Currently this is not possible, but you can see progress on supporting this feature in #108
