### ISSUE TITLE
Sample app checkbox bug

### ISSUE THREAD

**Issue by lectricas** [bignerdranch/expandable-recycler-view#241]
Compile the project, run it on your device. 
Uncheck some checkboxes and check one (ie third one)
Scroll down to the bottom. 
Scroll back.
Checkboxes checked in other absolutely random places.
damn this lib.

**Comment by paul-turner** [comment]
@lectricas Ah yes we never hooked up a listener to the checkbox, I'll submit a PR to disable it as we are not meaning to make changes to the crime from the list. Just meant to be a read only display for simplicity purposes with the sample.

**Comment by paul-turner** [comment]
Fixed by removing CriminalIntent Sample. There was no need for two samples and CriminalIntent was not being updated as development went on properly. Thank you for submitting this issue.
