### ISSUE TITLE
How to implement setOnClickListener for parent item, if they don't have any children..?

### ISSUE THREAD

**Issue by lakshmanbodduluru** [bignerdranch/expandable-recycler-view#248]
How to implement setOnClickListener for parent item, if they don't have any children..?

**Comment by lakshmanbodduluru** [comment]
Please Help me.

**Comment by paul-turner** [comment]
Hello,
Very similar to how you would with any viewholder, In your ParentViewHolder simply add an onClickListener to a view and make sure to override `shouldItemViewClickToggleExpansion` to false.

See an example here https://github.com/bignerdranch/expandable-recycler-view/blob/master/sampleapp/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/horizontal/HorizontalParentViewHolder.java
