### ISSUE TITLE
Programmatically calling expandParent(index) doesn't trigger ExpandCollapseListener

### ISSUE THREAD

**Issue by jagan999** [bignerdranch/expandable-recycler-view#249]
Hello,

First of all, thanks for providing this library. I'm a big fan of Big Nerd Ranch books for the nice flow of how a programming language is explained and the robustness of the code shown. Now, I am using your library in one of my projects but am a little stuck.

Here's the situation I have. I have a small Expand/Collapse icon to expand/collapse children of a parent. I've implemented expandView and collapseView in the parentviewholder and it works fine (Shows the collapse icon when parent is expanded and vice versa)

I also have scenarios where I need to programmatically expand the parent, hence use expandParent and it works fine. However, I'm unable to change the Expand/Collapse icon state when the parent is expanded using expandParent. Even if I've registered ExpandCollapseListener on the adapter, it doesn't get call backs when the parent is expanded through expandParent. Any suggestions? 

I looked up the code but it seems to only trigger the listener callbacks when the parent is expanded through clicking the entire card view.

**Comment by paul-turner** [comment]
Hi @jagan999, thank you for the compliments.

We did make the decision to not trigger the listener callback when expand/collapse is called programmatically. This was in order to prevent a cycle of callbacks (for example, Spinner does not do this and has constantly given us headaches).

What you might need to do is handle the icon changing at the `ParentViewHolder` level. When a programatic change is triggered you will still get a call to `onExpansionToggled` in the `ParentViewHolder` which will give you a chance to modify your view.

Let me know if that isn't clear!

**Comment by jagan999** [comment]
Thanks Paul. I tried your suggestion to extend the onExpansionToggled method to handle my logic for expand/collapse icon but this method is NOT called back when I call expandParent. Any thoughts?

**Comment by paul-turner** [comment]
Hmmm was the view possibly off screen? if that's the case you will not get the toggle, only the initial setting of the expand/collapse in `setExpanded`.

**Comment by jagan999** [comment]
The view is not off screen. I can still see the collapse/expand icon but my extended onExpansionToggled is never invoked and the collapse/expand icon is not in the desired state after the view is programmatically expanded.

**Comment by jagan999** [comment]
Got it working. I had not implemented setExpanded to indicate my initial state, hence the toggle didn't work. Now it works. Great. Appreciate the quick response and guidance.

**Comment by paul-turner** [comment]
@jagan999 Glad it worked out, I'll still take a peek at `onExpansionToggled` to make sure it works as I expect it to.
