### ISSUE TITLE
How to use json in this library?

### ISSUE THREAD

**Issue by lowfiend** [bignerdranch/expandable-recycler-view#251]
Ingredient beef = new Ingredient("beef");
        Ingredient cheese = new Ingredient("cheese");
        Ingredient salsa = new Ingredient("salsa");
        Ingredient tortilla = new Ingredient("tortilla");
        Ingredient ketchup = new Ingredient("ketchup");
        Ingredient bun = new Ingredient("bun");

        Recipe taco = new Recipe("taco", Arrays.asList(beef, cheese, salsa, tortilla));
        Recipe quesadilla = new Recipe("quesadilla", Arrays.asList(cheese, tortilla));
        Recipe burger = new Recipe("burger", Arrays.asList(beef, cheese, ketchup, bun));
        final List<Recipe> recipes = Arrays.asList(taco, quesadilla, burger);
        mAdapter = new RecipeAdapter(getActivity(), recipes);

I find sample code.
But I don't know how to parse json.

Is this library had any json sample code?

**Comment by dgreenhalgh** [comment]
@lowfiend Parsing JSON is outside of the scope of this library. For that you may want to look at [Gson](https://github.com/google/gson).

**Comment by lowfiend** [comment]
I mean how to parse json data then I can throw into RecipeAdapter

**Comment by lowfiend** [comment]
Now the library data is static.
The library support  dynamic data is perfect

**Comment by paul-turner** [comment]
@lowfiend using the `notifyParent/Child...` should allow you to dynamically add and remove data as you see fit. Soon we should also have available #89 which would give you an easy way to update data as a whole.
