### ISSUE TITLE
version 3 release

### ISSUE THREAD

**Issue by kashifandroiddev** [bignerdranch/expandable-recycler-view#253]
dear i am waiting for long time for you to publicly release 3 version and use AAR file 

when you will rease it thanks 

now i am using snapshot version

thanks for your help...

**Comment by paul-turner** [comment]
Hi @kashifandroiddev, Thank you for your patience.

We still have a couple more features that we want to roll into 3.0.0, the snapshot should allow you to continue development unharmed. If you are concerned about api changes while using the 3.0.0-SNAPSHOT build I would recommend pulling the 3.0.0 branch into a module of your library and compiling it with your project (or just pulling the AAR).

For a rough estimate of what is missing in 3.0.0 feel free to take a look at https://github.com/bignerdranch/expandable-recycler-view/milestone/6

**Comment by kashifandroiddev** [comment]
thanks

how i can dawnload snapshort aar file i did search every thing but could
not find any

thanks for your help

**Comment by paul-turner** [comment]
I've added a pre-release tag that I'll try to keep updated with the latest AAR version as we update them, this should help get you going: https://github.com/bignerdranch/expandable-recycler-view/releases/tag/v3.0.0-SNAPSHOT

**Comment by kashifandroiddev** [comment]
very thanks brother .....this is what i am loking ...............thanks
again /.......
