### ISSUE TITLE
Optimising for loop 

### ISSUE THREAD

**Issue by lucas34** [bignerdranch/expandable-recycler-view#260]
Hi,

All the for-each loop can be optimised by using the 'indexed' for loop. 

Should I do a PR for this ?
Lucas

**Comment by paul-turner** [comment]
Hi Lucas,

I will admit I'm not the most familiar with optimizations of for loops, but I can't seem to find consensus on indexed being marketed better.

Some examples of information I found with a quick search (I admit these are not the best sources but seem to give detailed information):
http://stackoverflow.com/questions/2113216/which-is-more-efficient-a-for-each-loop-or-an-iterator
Which shows that at compile time they will be quite similar, and then from Item 46 in [Effective Java][1] by Joshua Bloch :

> The for-each loop, introduced in release 1.5, gets rid of the clutter
> and the opportunity for error by hiding the iterator or index variable
> completely. The resulting idiom applies equally to collections and arrays:
```
 // The preferred idiom for iterating over collections and arrays
     for (Element e : elements) {
         doSomething(e);
     }
```
> 
> When you see the colon (:), read it as “in.” Thus, the loop above reads as
> “for each element e in elements.” Note that there is no performance penalty
> for using the for-each loop, even for arrays. In fact, it may offer a slight
> performance advantage over an ordinary for loop in some circumstances, as it
> computes the limit of the array index only once. While you can do this by
> hand (Item 45), programmers don’t always do so.

For this reason I'm leaning towards leaving things as-is, with maybe a pass at the current code to give it more uniformity (currently there is a mix of indexed and for-each in the code, should be for-each wherever possible).


Let me know what you think!

  [1]: http://www.amazon.com/Effective-Java-2nd-Joshua-Bloch/dp/0321356683

**Comment by lucas34** [comment]
The for-each loop will allocate an iterator where the index loop does not. But I agree the code is less readable.

When I look at the code yesterday, I saw you are using the indexed loop most of the time and only few times the for each.

**Comment by paul-turner** [comment]
@lucas34 Thanks Lucas, I think at least we need to take a look at the code and give it some consistency. I'll leave this issue up to track that effort. There is currently a lot of moving pieces with 3.0.0 work, so I might delay this change/effort until after that (since it can be in a patch release as it will not change any api's)
