### ISSUE TITLE
Package name start with upper case

### ISSUE THREAD

**Issue by lucas34** [bignerdranch/expandable-recycler-view#262]
Hi,

Not sure if you made it in a purpose or not but the following packages start with uppercase

- Adapter	
- Model
- ViewHolder

Regards,
Lucas

**Comment by paul-turner** [comment]
Hi @lucas34!
Thanks for the feedback, we noticed a little late but this is a change that has already happened in the 3.0.0 snapshot. I'll mark this in the milestone so that others can see this has been implemented.
