### ISSUE TITLE
Update isChecked in CrimeChild object

### ISSUE THREAD

**Issue by oscar6263** [bignerdranch/expandable-recycler-view#267]
I would like to hook up the check box in the expanded view to the CrimeChild checked data object.  Where would be the best place to do that?

**Comment by dgreenhalgh** [comment]
@oscar6263 In the CriminalIntent sample, the value of the CrimeChild's solved data is bound to the CrimeChildViewHolder in `CrimeExpandableAdapter.onBindChildViewHolder`. 

That said, we are deprecating the CriminalIntent sample as a part of the 3.0 release, so I'm going to go ahead and close this issue. If you have any more questions, feel free to let us know.
