### ISSUE TITLE
Reseting recycler view adapter is creating empty space

### ISSUE THREAD

**Issue by Ajibola** [bignerdranch/expandable-recycler-view#268]
When setting the adapter for the recycler iew again, it creates empty space which i have to smoothScroll to get the right position. What is causing the empty space?

```
                    contentRecyclerView.smoothScrollBy(0, height);
                    contentRecyclerView.smoothScrollToPosition(0);
```

**Comment by paul-turner** [comment]
@Ajibola How is the adapter being reset? is the recyclerview a fixed size? Not sure that this is something that the library is affecting if you are swapping out the entire adapter. What version of RecyclerView are you using?

**Comment by Ajibola** [comment]
The adapter does have a fixed size and is being reset by re-initializing it with a list. Using android.support.v7.widget.RecyclerView

**Comment by paul-turner** [comment]
Sorry, I meant what version of the support library (for example the current latest version is 24.2.1), If you are not defining it then it will be whatever version is defined by ExpandableRecyclerView, which then I need to know what version of the Library you are using.

**Comment by Ajibola** [comment]
Using support library 24.2.0

**Comment by dgreenhalgh** [comment]
@Ajibola I just tried rolling back to support lib 24.2.0 and was unable to reproduce. If your workaround is to smooth scroll to position 0, could this be a problem with some padding or ItemDecoration you've added? It may be useful to have some pictures.
