### ISSUE TITLE
Move item from parent 1 to parent 2

### ISSUE THREAD

**Issue by hatpick** [bignerdranch/expandable-recycler-view#274]
Is it possible to do this without re-doing the dataset assignment in the adapter and a call to notifyDataSetChanged?

**Comment by XxGoliathusxX** [comment]
If you add an item to another parent and remove it from the first you have to call atleast notifyDataSetChanged()

**Comment by hatpick** [comment]
I know that, I want to apply item moved animations

**Comment by paul-turner** [comment]
@hatpick Are you trying to move a child from one parent to another? If so you'll have to do a `notifyChildItemRemoved()` and then `notifyChildItemInserted()`. Currently there is no notify method for moving a child from one parent to another, though that may be something we consider for a future version. This will at least give you a fade out/fade in for your change.

**Comment by hatpick** [comment]
Great, thanks.

**Comment by dgreenhalgh** [comment]
Closing as long as this is resolved 👍
