### ISSUE TITLE
Change Expandable State at real time

### ISSUE THREAD

**Issue by mitko9000** [bignerdranch/expandable-recycler-view#275]
Is it possible when populating the recycleView onBind period or anywhere else to change the default expandable state given by the interface ParentListItem -> isInitiallyExpanded by default all of my header items are false (closed) but I want when entering data to the field to decide wheter or not should expand or not. 

Is that possible and If so how can I achieve it because I tried to do it on bind but I get the error Cannot call this method while RecyclerView is computing a layout or scrolling

**Comment by paul-turner** [comment]
Hi @mitko9000 do you maybe mean to have the ability to expand/collapse the parent items programmatically? If so, take a look at https://github.com/bignerdranch/expandable-recycler-view/blob/master/expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/Adapter/ExpandableRecyclerAdapter.java#L317-L424

That has expand/collapse methods on the adapter that you can use to trigger a change after the initialization.

**Comment by mitko9000** [comment]
Hi @paul-turner  I have seen those methods but every time I invoke them I get recycleView is not ready crash when its the best time to expand the items I want programmatically ?

**Comment by paul-turner** [comment]
Do you have a snippet showing when and what you are currently doing? Also maybe a copy of the exception to see. Version information would also help, what version of the support library, and what version of ExpandableRecyclerView.

**Comment by mitko9000** [comment]
For example:

```
@Override
    public void onBindParentViewHolder(HistoryParentViewHolder hisotryParentViewHolder, int i, ParentListItem parentListItem) {

        History history = (History) parentListItem;

        if(currentDate.equals("TODAY") || currentDate.equals("YESTERDAY"))
        {
          expandParent(0);        
}

}
```

**Comment by paul-turner** [comment]
I see, seems like dataSetChanges should not be triggered during onBind but I'm not familiar with that error. 

Why not have the logic of `if(currentDate.equals("TODAY") || currentDate.equals("YESTERDAY"))` inside your `isInitiallyExpanded()` method? seems like you are trying to have them expand based on that logic. Otherwise, I'd say call for your item to expand in onCreateView after you set the adapter on the recyclerView.

For the call to `expandParent(0)` are you sure the parent has child items? seems odd for it to not expand at all. (for example, if you remove this expansion code and just click on the item, does it expand?)

**Comment by mitko9000** [comment]
@paul-turner Hi paul I cant use that logic inside the ParentViewholder because there I dont have access to the data that its going to be displayed I will try with the onCreateView, the whole Idea is when the adapter loads the items needed I need to parse the headers and everywhere on those headers where the date equals TODAY or YESTERDAY to expand that item I will try some solutions next week and keep you updated when I find a solution about that.

Yeah expandParent(0) do nothing because at this state the internal list is with item count of zero.

Regards,
Mitko

**Comment by paul-turner** [comment]
OK, seems there are two tweaks that need to be made. One, the data should be available inside the ParentListItem (Not the ParentViewHolder), and you can hold that logic of initial expansion in `isInitiallyExpanded()`. Two, you'll need to have children already or else there is nothing that will change when you call for expandParent() (also if you have it initiallyExpand to true, you will need to have the children there).  If there are changes to the data you will need to call the corresponding notifyParent or notifyChild methods, and it seems those cannot be called while binding.

Unfortunately it does not seem at this time that there is something wrong with the library, just need some small changes on your data side. Best of luck finding a solution, let me know if you run into any issues with the library.

**Comment by mitko9000** [comment]
@paul-turner I changed my logic so I can input as parameter weather or not I want this item to be expanded and it worked like charm
