### ISSUE TITLE
Gradle 'com.bignerdranch.android:expandablerecyclerview:3.0.0-RC1' doesn't compile ParentListItem etc

### ISSUE THREAD

**Issue by bene25** [bignerdranch/expandable-recycler-view#282]
Gradle 'com.bignerdranch.android:expandablerecyclerview:3.0.0-RC1' doesn't compile ParentListItem etc

**Comment by dgreenhalgh** [comment]
`ParentListItem` has been renamed to `Parent` in 3.0.0. See the full release notes [here](https://github.com/bignerdranch/expandable-recycler-view/releases/tag/v3.0.0-RC1).
