### ISSUE TITLE
Added Header/Footer

### ISSUE THREAD

**Issue by GauravP123** [bignerdranch/expandable-recycler-view#283]
How i can add header and footer into recycler view list

**Comment by mitko9000** [comment]
Hi @GauravP123 ,
The sample in this library is showing you how

**Comment by dgreenhalgh** [comment]
@GauravP123 Could we have some more information about what kind of header or footer you are trying to create?

**Comment by GauravP123** [comment]
so basically any type of view so it will look like 
--HeaderView--

--ParentView 1--
---ChildView of parentview1---
--ParentView2--
---ChildView of parentview2---

---FooterView-----

**Comment by parcool** [comment]
@GauravP123 @dgreenhalgh  we need it support more type of view,it will look like:
--HeaderView--

--ParentView 1--
---ChildView1 of parentview1---
---ChildView2 of parentview1---
--ParentView2--
---ChildView of parentview2---
--**ParentView without childView,Actually it's not a parentView**--
--ParentView3--
---ChildView of parentview3---
---ChildView of parentview3---

---FooterView-----

**Comment by dgreenhalgh** [comment]
@GauravP123 @parcool In these examples, the recommended solution is to use a Parent of a different view type with no children.
