### ISSUE TITLE
gridLayout childs

### ISSUE THREAD

**Issue by johny-mdl** [bignerdranch/expandable-recycler-view#284]
It is possible to make childs of a expandable list display in the same parent column of the gridLayout?
If a the recycler view take a gridLayout manager the parents are displayed in the grid correctly, but when i click on one of them, the chils of that element expand in diferent grids columns and i want that the childs expand in the same parent's column.

**Comment by dgreenhalgh** [comment]
We don't currently officially support layout managers other than `LinearLayoutManager`. Support for `GridLayoutManager` is being tracked at #151.
