### ISSUE TITLE
Expanding only one category at a time

### ISSUE THREAD

**Issue by ZahidRasheed** [bignerdranch/expandable-recycler-view#286]
How can we make it work so that when user select a category, it collapses other categories?

**Comment by HuaJianJiang** [comment]
hi,there, you can check my implemented lib, welcome pull request ,issues ,fork,thanks!
https://github.com/HuaJianJiang/ExpandableRecyclerView

**Comment by guulshark** [comment]
When expanded one parent for collapsing others you can use ExpandCollapseListener.
`@Override
public void onParentExpanded(int parentPosition) {
    for (int i = 0; i < adapter.getParentList().size(); i++) {
        if (i != parentPosition) {
            adapter.collapseParent(i);
        }
    }
}`

**Comment by dgreenhalgh** [comment]
Closing as resolved. Let us know if you have any other questions!
