### ISSUE TITLE
Bug: detached ViewHolder not sync parent expand status sometimes

### ISSUE THREAD

**Issue by huajianjiang** [bignerdranch/expandable-recycler-view#291]
When you call expandParent() 、collapseParent、expandAllParents、collapseAllParents ，sometimes someone parent Viewholder not sync parent expand status even you scroll RecyclerView.

RecyclerView not call onBindViewHolder for detached or scrap view, you can try ,this bug is hard to find.when collapseViews() or expandViews() is called,model layer parentWrapper is update parent expand status,but viewholder layer 's parent not(it is detached or scrap at this time), when user scroll the RecyclerView or even notifyItemChanged(flatParentPosition) ,some previous flatParentPosition ViewHolder not rebind!

PS: Thanks !

Hope your reply!

**Comment by paul-turner** [comment]
Hi @huajianjiang Based on #287 seems like you've found a solution for your fork of the library. I'll be attempting to go the route of calling `notifyItemChanged` and see the results from that. Your other comment seems to suggest that will not work completely. I'd love to see a sample that recreates this issue consistently!

I'm going to close this issue as a duplicate, I encourage you to continue the conversation in #287
