### ISSUE TITLE
Context not available

### ISSUE THREAD

**Issue by Cataalinn** [bignerdranch/expandable-recycler-view#292]
Please add Context getter inside Parent and Child ViewHolder.

**Comment by JanuszHain** [comment]
Can't you do it yourself?

**Comment by Cataalinn** [comment]
Yeah, why not, but i don't know if is already planned or implemented this feature in order to make a pull request.

**Comment by dgreenhalgh** [comment]
@Cataalinn No need to make a PR here. You should have access to Context from the View passed into your ViewHolder implementation. See RecipeViewHolder and IngredientViewHolder in the sample for an example.
