### ISSUE TITLE
Expand/Colapse bug

### ISSUE THREAD

**Issue by Cataalinn** [bignerdranch/expandable-recycler-view#293]
Please remove expand click listener from xml parent on ParentViewHolder. Let user to decide what view will deal with that process.

**Comment by dgreenhalgh** [comment]
@Cataalinn The click listener built into ParentViewHolder is for convenience and can be overridden by overriding `ParentViewHolder.shouldItemViewClickToggleExpansion`. Does this answer your question?

**Comment by Cataalinn** [comment]
@dgreenhalgh Kind of, but i need to read the documentation to know that as first time use. In my opinion is better if is false by default.

**Comment by paul-turner** [comment]
@Cataalinn Thank you for the suggestion, if this comes up more often we'll consider changing it. 

Since this library is meant to give a quick path for an expandable RecyclerView, it seems relevant to keep the default behaviour for developers first starting with this library.
