### ISSUE TITLE
I got this IllegalStateException when use it combine XRecyclerView!

### ISSUE THREAD

**Issue by parcool** [bignerdranch/expandable-recycler-view#295]
exception in logcat:
`java.lang.IllegalStateException: Parent not wrapped
W/System.err:     at com.bignerdranch.expandablerecyclerview.model.ExpandableWrapper.getWrappedChildList(ExpandableWrapper.java:90)
W/System.err:     at com.bignerdranch.expandablerecyclerview.ExpandableRecyclerAdapter.updateExpandedParent(ExpandableRecyclerAdapter.java:703)
W/System.err:     at com.bignerdranch.expandablerecyclerview.ExpandableRecyclerAdapter.parentExpandedFromViewHolder(ExpandableRecyclerAdapter.java:420)
W/System.err:     at com.bignerdranch.expandablerecyclerview.ExpandableRecyclerAdapter$1.onParentExpanded(ExpandableRecyclerAdapter.java:446)
W/System.err:     at com.bignerdranch.expandablerecyclerview.ParentViewHolder.expandView(ParentViewHolder.java:186)
W/System.err:     at com.bignerdranch.expandablerecyclerview.ParentViewHolder.onClick(ParentViewHolder.java:158)
W/System.err:     at android.view.View.performClick(View.java:5207)
W/System.err:     at android.view.View$PerformClick.run(View.java:21177)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:148)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5438)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)`

and the XRecyclerView at [here](https://github.com/jianghejie/XRecyclerView)

**Comment by parcool** [comment]
i need refresh and load more,so i use [XRecyclerView ](https://github.com/jianghejie/XRecyclerView)replace Android.RecyclerView,but when i clicked the last item and the excetion occured and crashed!
i know this is not about your bug in the library,but can you give me some suggestion?

**Comment by dgreenhalgh** [comment]
@parcool Based on the information provided, my guess would be that XRecyclerView is interfering with indexing and there's no communication between the view and the adapter. That said, Expandable RecyclerView relies on RecyclerView, and, as such, we do not support libraries like XRecyclerView.
