### ISSUE TITLE
How do I use two LayoutManager

### ISSUE THREAD

**Issue by a1018875550** [bignerdranch/expandable-recycler-view#296]
I wan to use LinearLayoutManager for parent, and I want to use StaggeredGridLayoutManager for child;
How do I achieve this?

**Comment by dgreenhalgh** [comment]
@a1018875550 Expandable RecyclerView currently only supports use of LinearLayoutManager. 

Note that RecyclerView has a 1:1 relationship with a LayoutManager, so rather than having multiple LayoutManagers, you would just have a single, more complex LayoutManager.
