### ISSUE TITLE
when the data is big enough, notifyItemRangeInserted will lead some mistake.

### ISSUE THREAD

**Issue by tgiwu** [bignerdranch/expandable-recycler-view#297]
when the data is big enough click the last few parentItem, child item is shown at once, that is normal, but when you collapse it and expand it again, there will be some child item is empty, none of data is filled.

**Comment by paul-turner** [comment]
@tgiwu Sorry for the late reply here, How big is big in this case?
Any chance this can be recreated with one of our samples? Or can you provide a short sample/snippet of the issue?
Is this a data set with a lot of parents or a lot of children inside the parents?

**Comment by tgiwu** [comment]
@paul-turner Thanks for reply and sorry for the late reply here, It is not happen recently, I will tell you when it happen again. Thanks again.
