### ISSUE TITLE
Unsupported SwipeRefreshLayout

### ISSUE THREAD

**Issue by Geocomt** [bignerdranch/expandable-recycler-view#306]
SwipeRefreshLayout don´t work to update a Expandable RecyclerView.

This work:
`swipeRefreshLayout.setRefreshing(true);` 

But if insert the listener:
```java
swipeRefreshLayout.setOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener() {
            @Override
            public void onRefresh() {
                updateData();
            }
        });
```
Never is called.

**Comment by paul-turner** [comment]
Threw together a quick sample, my onRefresh gets called just fine in this branch https://github.com/bignerdranch/expandable-recycler-view/tree/PAUL/swipe-to-refresh-test
(Note to future people, I'll probably delete that branch in 2-3 months, all that was done was a SwipeRefreshLayout was added to the layout and a OnRefreshListener set in `VerticalLinearRecyclerViewSampleActivity`)

Go ahead and reopen this issue if you have more details on how to reproduce!
