### ISSUE TITLE
Is it possible to find out which parent is currently static

### ISSUE THREAD

**Issue by ZahidRasheed** [bignerdranch/expandable-recycler-view#309]
I would like to know which of the category is selected so doing instrumentation testing I can make sure this is the true case....

**Comment by paul-turner** [comment]
@ZahidRasheed What do you mean by a parent being static? I haven't done many Espresso tests on RecyclerViews but ExpandableRecyclerView shouldn't get in the way of your instrumentation testing, you might need to create some helpers to help distinguish between children and parent viewholders. (or to translate your list into a flat list similar to `mFlatItemList`)
