### ISSUE TITLE
How keep open a specified number of children items?

### ISSUE THREAD

**Issue by volkdown** [bignerdranch/expandable-recycler-view#312]
How can I in the colapsed condition parent item show child items in an amount equal to three? And when click on parent item, so that its condition changes to expanded show all its child items.

**Comment by paul-turner** [comment]
Hi @volkdown,

Sorry for the slow response. This is currently not really supported in expandableRecyclerView. The only way I can think of it right now is to make your ParentViewHolder look like it is a ParentViewHolder + 3 ChildrenViewHolders. That way when it expands it will only add the rest beyond 3, and when collapsed look like a parent with 3 children.

**Comment by volkdown** [comment]
Thanks but I already did it. I have done three children and left them always open. When opening I add items in children items.

**Comment by volkdown** [comment]
It seems to me that this issue deserves your attention
https://github.com/bignerdranch/expandable-recycler-view/issues/328

**Comment by paul-turner** [comment]
Glad you got it working. I'm working up my way through the issues chronologically.
