### ISSUE TITLE
adapter item update

### ISSUE THREAD

**Issue by JeckChou** [bignerdranch/expandable-recycler-view#315]
have any interface to remove or insert an item ?

**Comment by paul-turner** [comment]
Hi there, take a look at the horizontal sample, it has many examples of adding and removing and using the ExpandableRecyclerView-specific notify methods: 

https://github.com/bignerdranch/expandable-recycler-view/blob/master/sampleapp/src/main/java/com/bignerdranch/expandablerecyclerviewsample/linear/horizontal/HorizontalLinearRecyclerViewSampleActivity.java#L205
