### ISSUE TITLE
When expanding a parent, scroll up if children are not visible

### ISSUE THREAD

**Issue by paour** [bignerdranch/expandable-recycler-view#319]
In the current (2.1.1) implementation, expanding a parent that is at the bottom of the visible portion of the list results in newly-populated children not to be visible because they're offscreen.

To remedy this and avoid a manual scroll, if the newly-populated children's height is greater than the visible space below the patent, the list should be scrolled up so that all the newly-populated children are visible, or the parent is scrolled to the top of the visible area.

**Comment by Corical** [comment]
I was on my way to ask exactly this, thanks. Bump*

**Comment by paour** [comment]
Judging from the lack of response on this and many other issues and PRs, this project is sadly being neglected.

**Comment by Corical** [comment]
I see some solutions was suggested in issue #156 

I decided to go with the Custom layout manager, last suggestion, seem to be working.

**Comment by paul-turner** [comment]
Hi @paour and @Corical, sorry for the delayed response.

As mentioned this feature is being tracked in #156, one of the bigger problems is that this is more a behaviour of the LayoutManager which we have yet to make a custom version for XRV, contributions are welcome (and the issue has been marked as needing help).
