### ISSUE TITLE
How to update the child item from the parent item ? 

### ISSUE THREAD

**Issue by MickaelRomaniello** [bignerdranch/expandable-recycler-view#324]
Hi everyone,

I have my parent item with a checkbox and i want that when i check the checkbox, the checkbox of the child pass to checked but the problem is that for now i didn't find anything to this, because if i try to access the child in the parent, i will "itemView may not be null", i didn't click on the child for now.

How to update the child item from the parent item ? 

Thank you for your help

**Comment by paul-turner** [comment]
Hi @MickaelRomaniello,
You'll probably want to do something like the following:
- Update your child model to reflect the checked/unchecked state
- Get the index of your parent, and the index of your child/children within that parent
- Call `notifyChildChanged` or `notifyChildRangeChanged` with that information.

This should trigger the views to update if they are displaying, and if not they should be correct when they are bound.

**Comment by vandanabpatel** [comment]
How to update the child list at parent position (0)?
