### ISSUE TITLE
Not able to remove views

### ISSUE THREAD

**Issue by karanjatav** [bignerdranch/expandable-recycler-view#326]
I ve spent hours to remove items from parent as well as child list but somehow i m now able to do it. I m new to android programming so could you plz help me out with that. I didnt know where to contact you so i made an issue here.

**Comment by paul-turner** [comment]
@karanjatav You'll want to remove the objects from your list, and then call `notifyChildRemoved` or `notifyParentRemoved`. Please look at the sample application for an example of this in action (the horizontal sample has all the removes working).
