### ISSUE TITLE
How detect type child item or parent item for pagination

### ISSUE THREAD

**Issue by volkdown** [bignerdranch/expandable-recycler-view#328]
Hello, I need to load large amounts of data to the list. So I have to use pagination. How can I determine what type item in  method onScrolled to count how many items scrolled. I'm downloading the data from the number of parent elements.Now in the method I get the sum of the number scrolled  parent and child elements. My use of the method onScrolled:
http://prntscr.com/e4a67e
Thank you in advance.

**Comment by ahmedsalemelzeiny** [comment]
@volkdown  Had you solved this issue ? i'm trying also to make pagination in child holder and my problem to get how many items in child scrolled. there is no option for get child recycle to know that ?

**Comment by volkdown** [comment]
No, I still could not find a solution (I put this question to the release of the application

**Comment by paul-turner** [comment]
@volkdown Sorry for the delay,
If all you need to do is determine the type, and have the flattened index, then you should be able to call `getItemViewType` on your adapter with that index, and it will give you an integer for each type.

Let me know if that helps!

**Comment by volkdown** [comment]
Hello! Sorry but this method not work.

**Comment by paul-turner** [comment]
Hmm, thats not good to hear. But I'm glad you found a solution. If you have a bug report for the method not working (ideally with how to recreate the issue), I'd love to hear it in another issue.

**Comment by dudayefahmad** [comment]
i have same problem @volkdown , will you share what your solution. Thanks in advance
