### ISSUE TITLE
How to show View only in first child

### ISSUE THREAD

**Issue by htooaunghlaing** [bignerdranch/expandable-recycler-view#329]
I need to show a View in every first item for every child list.So, I add a View and set it visibality to "gone", and set Visible only for the first item.But, it effect to other child items.Is there any way for that.Thanks.

```
 @UiThread
    @Override
    public void onBindChildViewHolder(@NonNull IngredientViewHolder ingredientViewHolder, int parentPosition, int childPosition, @NonNull Ingredient ingredient) {
        ingredientViewHolder.bind(ingredient);

         if(childPosition == 0){
            IngredientViewHolder.firstView.setVisibility(View.VISIBLE);
        }
    }
```

**Comment by JoseArceDev** [comment]
Hey @htooaunghlaing, I have done it 

`    private void updateCollapsedParent(@NonNull ExpandableWrapper<P, C> parentWrapper, int flatParentPosition, boolean collapseTriggeredByListItemClick) {
        if (!parentWrapper.isExpanded()) {
            return;
        }

        List<ExpandableWrapper<P, C>> wrappedChildList = parentWrapper.getWrappedChildList();
        if (wrappedChildList != null && wrappedChildList.size() == 1) {
            return;
        }

        parentWrapper.setExpanded(false);
        mExpansionStateMap.put(parentWrapper.getParent(), false);

        if (wrappedChildList != null) {
            int childCount = wrappedChildList.size();

            for (int i = childCount - 1; i >= 1; i--) {
                mFlatItemList.remove(flatParentPosition + i + 1);
            }

            notifyItemRangeRemoved(flatParentPosition + 1, childCount);
        }

        if (collapseTriggeredByListItemClick && mExpandCollapseListener != null) {
            mExpandCollapseListener.onParentCollapsed(getNearestParentPosition(flatParentPosition));
        }
    }` 

`    private void updateExpandedParent(@NonNull ExpandableWrapper<P, C> parentWrapper, int flatParentPosition, boolean expansionTriggeredByListItemClick) {
        if (parentWrapper.isExpanded()) {
            return;
        }

        parentWrapper.setExpanded(true);
        mExpansionStateMap.put(parentWrapper.getParent(), true);

        List<ExpandableWrapper<P, C>> wrappedChildList = parentWrapper.getWrappedChildList();
        if (wrappedChildList != null) {
            int childCount = wrappedChildList.size();

            mFlatItemList.remove(flatParentPosition + 1);
            notifyItemRangeRemoved(flatParentPosition + 1, 1);

            for (int i = 0; i < childCount; i++) {
                mFlatItemList.add(flatParentPosition + i + 1, wrappedChildList.get(i));
            }

            notifyItemRangeInserted(flatParentPosition + 1, childCount);
        }

        if (expansionTriggeredByListItemClick && mExpandCollapseListener != null) {
            mExpandCollapseListener.onParentExpanded(getNearestParentPosition(flatParentPosition));
        }
    }`

**Comment by JoseArceDev** [comment]
Hey @htooaunghlaing, I have done it, I updated these methods **updateExpandedParent()** and **updateCollapsedParent**, you can see all file [here](https://gist.github.com/JoseArceDev/075693594c0f77f8109f9f8321bafb9e)

**Comment by htooaunghlaing** [comment]
Controlling in Child is a little messy, it i control in ParentView and it is OK.

**Comment by htooaunghlaing** [comment]
Controlling in Child is a little messy, it i control in ParentView and it is OK.
