### ISSUE TITLE
Is possible add another recyclerView in the ChildView

### ISSUE THREAD

**Issue by darKnightGH** [bignerdranch/expandable-recycler-view#334]
when I expand the ExpandableRecyclerView, I would like to fixed the screen and the user could scroll the contents of the child.
I thought about using the child as recyclerview, is it possible?

Where should I inflate my xml?

thanks

**Comment by dgreenhalgh** [comment]
What is the scroll direction that you would like your child RecyclerView to scroll in? If it's running in the same direction as your primary RecyclerView, you may want to reconsider as this is a confusing user experience.

Either way, take a look at the samples - they show View inflation at the adapter level in the `onCreateChildViewHolder` and `onCreateParentViewHolder` methods.

**Comment by vishalpatelbacancy** [comment]
suppose i have grid instead of   verticle recyclerview inside Child the how it possible to handle
i cant understand
