### ISSUE TITLE
What if I want just parent with no child.Sorry if the question is solved,need help. Thank you

### ISSUE THREAD

**Issue by benevolent13** [bignerdranch/expandable-recycler-view#336]
I have a recycleview mixed one with only some parent other as usual simple recycle view item without child.

**Comment by dgreenhalgh** [comment]
@benevolent13 Your Parent can have an empty list of children. 

Take a look at the sample where we set up our parents, passing them lists of children. You can simply pass an empty list there.

**Comment by benevolent13** [comment]
Thank you so much and also i found it. :)
