### ISSUE TITLE
How to support multiple level of expand

### ISSUE THREAD

**Issue by ahmedsalemelzeiny** [bignerdranch/expandable-recycler-view#341]
In my application i have Parent View, than Child , than Children of child.

How to make this using lib.

**Comment by ahmedsalemelzeiny** [comment]
@paul-turner Any update ?

**Comment by paul-turner** [comment]
Sorry @ahmedsalemelzeiny, this is not possible with the current library and won't be a focus for us to implement in the near future. :(
