### ISSUE TITLE
How Read Json from webService

### ISSUE THREAD

**Issue by iman100** [bignerdranch/expandable-recycler-view#353]
How do parents and child to read just JSON web service (phpmyadmin)??? i can,t find her example .
Are you an example, do you? Please link or guide me

**Comment by dgreenhalgh** [comment]
@iman100 This library is web service agnostic. Take a look at `ExpandableRecyclerAdapter` and the collection that it takes in. Deserializing your data is outside of the scope of Expandable RecyclerView just like a regular RecyclerView.
