### ISSUE TITLE
Option to have parents open on load

### ISSUE THREAD

**Issue by scottyab** [bignerdranch/expandable-recycler-view#36]
It would be great to be able to define one (or more) parents to be expanded when the adapter first loads. Great library btw thanks

**Comment by rbro112** [comment]
Hopefully I can get around to adding that soon. Feel free to fork it and work on it if you get a chance

**Comment by rbro112** [comment]
An easy solution to this could be an overloaded constructor in ```ParentObject``` taking in a boolean value for the expanded state. Set that value as mIsExpanded in the constructor and the item will appear expanded as default.

**Comment by scottyab** [comment]
Sounds good solution to me.

**Comment by Winghin2517** [comment]
Hello I was wondering if this was implemented? I saw a method to set the expanded flag in the ParentViewHolder class but it doesn't seem to work for me under onBindParentViewHolder: 

 if (position == 2) {
            Log.e("position2", "position 2 expanded");
            parentViewHolder.setExpanded(true);
        } else if (position == 3) {
            Log.e("position3", "position 3 NOT expanded");
            parentViewHolder.setExpanded(false);
        }

**Comment by RedEagle07** [comment]
@Winghin2517 Have you managed to make it work?
