### ISSUE TITLE
Expanded state lost in the Criminal Intent sample app

### ISSUE THREAD

**Issue by efarraro** [bignerdranch/expandable-recycler-view#38]
Noticed that in the Criminal Intent app that the expansion state doesn't persist through rotation.  Thought the adapter didn't support it, but then realized it does, but the the state wasn't restored by the fragment.  

Filed https://github.com/bignerdranch/expandable-recycler-view/pull/37 for a possible fix.

Thanks for creating this library!

**Comment by paul-turner** [comment]
Fixed by #42
