### ISSUE TITLE
Travis builds are not running

### ISSUE THREAD

**Issue by paul-turner** [bignerdranch/expandable-recycler-view#39]
Probably due to the change from a private repo to a public one, the travis badge also seems to be invalid.

**Comment by kurtisnelson** [comment]
paul-turner += :toilet: :toilet:

**Comment by rbro112** [comment]
Any way to get this fixed? I've only used travis once with Matt when we were setting up the repo.

**Comment by paul-turner** [comment]
Fixed in #46
