### ISSUE TITLE
notifyItemRangeRemoved does not work?

### ISSUE THREAD

**Issue by b1acKr0se** [bignerdranch/expandable-recycler-view#41]
So I tried to remove a parent object and it seemed that none of the notify methods worked. ```notifyDataSetChanged``` had no effect. ```notifyItemRemoved``` and ```notifyItemRangeRemoved``` animated the deletion but after that the item stayed where it was. I had to refresh the RecyclerView to know the changes. Did I miss something?

**Comment by rbro112** [comment]
#45 goes along with this.

**Comment by dasheck0** [comment]
Just to let you know: I want to use this library in several (some also productive) projects. Hence this feature/bugfix is highly appreciated.

**Comment by paul-turner** [comment]
We'll be trying to get this in soon.

**Comment by mzgreen** [comment]
I'm not sure why did you complicate this library. I implemented exactly same behavior without any wrappers, helpers and using only one list. Even saving state is simpler because it's not in adapter at all. Could you explain why do you need all these things?

**Comment by rbro112** [comment]
@mzgreen Have you forked or pushed the way you implemented the library on github? I'd like to check out your implementation and either see where we can improve this one or where I can explain my reasoning for some of the decisions made.

**Comment by mzgreen** [comment]
@rbro112 Not yet. It's a part of my bigger app. I will push a sample app with my implementation on Github as soon as I get back home.

**Comment by mzgreen** [comment]
Here is my demo project: https://github.com/mzgreen/ExpandableRecyclerDemo
Maybe I'm missing something but it seems to be working :)

**Comment by dgreenhalgh** [comment]
Resolved in 2.0.0.
