### ISSUE TITLE
Should add `parentObject` as param in `onBindChildViewHolder`

### ISSUE THREAD

**Issue by wliu6v** [bignerdranch/expandable-recycler-view#43]
I don't know how to get the parent object in `onBindChildViewHolader` method. And I think it will be useful when parent object have an effect on child object.

I try to modify the code like this:

	@Override
	public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
		if (mExpandableRecyclerAdapterHelper.getHelperItemAtPosition(position) instanceof ParentWrapper) {
			...
			...
		} else {

			Object child = mItemList.get(position);
			ParentObject parent = null;
			for (ParentObject p : mParentItemList) {
				if (p.getChildObjectList().contains(child)) {
					parent = p;
					break;
				}
			}

			onBindChildViewHolder((CVH) holder, position, child, parent);
		}
	}

**Comment by rbro112** [comment]
The ```ChildViewHolder``` class can be modified to store a reference to the Parent. This wouldn't be too hard and could be added in the constructor or as a ```setParentObject(ParentObject parentObject)``` inside ```ChildViewHolder```. Then, when the user creates the list of ParentItems, they could add the reference to the parent object in each.

**Comment by paul-turner** [comment]
Closing this issue, if this request comes up again we will consider adding it to the `onBindChildViewHolder` method. As it is now you can have your `ChildObject` store a reference to his parent and access that as needed.
