### ISSUE TITLE
There is no public method to change data.

### ISSUE THREAD

**Issue by Ivolian** [bignerdranch/expandable-recycler-view#44]
There is no public method to change mParentItemList or mItemList.
How can I do sth like loadmore?

**Comment by Ivolian** [comment]
Does anyone has good ideas?
Now I implement load more function by creating a new ExpandableRecyclerAdapter
when I get data from server and it's poor.

**Comment by paul-turner** [comment]
You are correct, currently there isn't a good way to do this. 
There should eventually be an API to make changes like you describe.

**Comment by rbro112** [comment]
I'll be addressing this issue in #45

**Comment by dgreenhalgh** [comment]
Resolved in 2.0.0.

**Comment by corclark** [comment]
Are there any examples of how to update the data in the mParentItemList before calling the notify methods? I have so far been unable to use any of the add/addAll type methods because of the generic.

**Comment by paul-turner** [comment]
@corclark it's a little disorganized but [HorizontalLinearRecyclerViewSampleActivity](https://github.com/bignerdranch/expandable-recycler-view/blob/master/sampleapp/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/horizontal/HorizontalLinearRecyclerViewSampleActivity.java) shows each of the notify methods in action

**Comment by scottdurica** [comment]
@paul-turner 
I looked through the HoriontalLinearRecyclerViewSampleActivity but wasn't able to find a update the whole list.  I'm pulling data from a server using Retrofit and would like to update the recycler view when the data is returned.  Normally I would just pass a null value to my adapter and then have a method like

`
    public void swapData(ArrayList<Movie> newList) {

        mDataList.clear();
        mDataList.addAll(newList);
        notifyDataSetChanged();
    }
`
 in my adapter to update the list.  Is that possible, or do I have to wait to initialize the adapter until I get the data from the server?

**Comment by paul-turner** [comment]
Hi @scottdurica 
You are correct, right now we don't have a whole list refresh, thats being tracked in #89. I think current work arounds are to swap the entire adapter using [swapAdapter()](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.html#swapAdapter(android.support.v7.widget.RecyclerView.Adapter, boolean)), that might help get you close to what you need until we deliver #89.
