### ISSUE TITLE
notifyDataSetChanged() or similar methods do not work.

### ISSUE THREAD

**Issue by rbro112** [bignerdranch/expandable-recycler-view#45]
When notifyDataSetChanged() or any similar methods are called, the new dataset is not displayed. This is due to the ExpandableRecyclerAdapterHelper not refreshing the data. We should add a method to refresh the data as a whole or at a certain position since I believe we can't directly override notifyDataSetChanged().

**Comment by rbro112** [comment]
#41 will be solved by this.

**Comment by dgreenhalgh** [comment]
Resolved in 2.0.0.
