### ISSUE TITLE
Specify expanding container in parent

### ISSUE THREAD

**Issue by dasheck0** [bignerdranch/expandable-recycler-view#50]
Hi,

currently children are expanded from the bottom. But I would like to specify a container, which expands as I click on the parent. Let's say I have three containers in my parent namely a header, a main container and a footer, which are layouted horizontally. When I click on the parent the main container, which is in the middle should open moving the footer down as well (not overlapping it). 

I'd like to hear your thoughts on that idea. Maybe I can help you and implement it myself if you are (too) busy.

Best regards
dasheck

**Comment by paul-turner** [comment]
Having a hard time following the situation you describe. Maybe some quick drawings showing the before and after of what you want would help clarify?

**Comment by dasheck0** [comment]
No problem at all. I will add some mockups when I get home.

**Comment by paul-turner** [comment]
Thanks @dasheck0 that cleared it up. Unfortunately I don't see that being in our roadmap right now, changes a lot about the behaviour of our content and expansion. Might be a better fit for a custom solution vs something to be rolled into this library.

**Comment by samy-baili** [comment]
Hi guys,
Dasheck, did you find some workaround ?

Samy

**Comment by dasheck0** [comment]
@samy-baili Not so far. Fortunately we changed the way the container behaves, which made the request obsolete. Still as fas as I know there is no library, which provides proper and flexible item expansion for lists and/or recyclerviews.

**Comment by samy-baili** [comment]
Ok too bad.
Thank you very much for your reactivity
