### ISSUE TITLE
Add a way to iterate over all items

### ISSUE THREAD

**Issue by mzgreen** [bignerdranch/expandable-recycler-view#51]
Right now items are removed from the list when it's collapsing. It would be nice if you would add a way to iterate over all items (parents and their children) no matter if the list is expanded or collapsed.
My usecase is this:
I'm implementing single selection for nav drawer. Everything works ok when list is expanded. But when I do the following:
1. expand some item
2. select subitem
3. collapse previously expanded item
4. select some parent item
Parent item gets selected but I have no way to inform collapsed subitem that it should unselect itself.

**Comment by tsuharesu** [comment]
I have the same "problem". My solution was to create a variable that knows which object is currently selected and updating as a new one is selected. Also, I save on a preference the *id* of this object so I can check there if this object should be selected or not.

**Comment by dgreenhalgh** [comment]
In 2.0, we're planning on exposing the full item list; stay tuned. In the meantime, you could iterate through the parent list and construct the total list by getting each parent's children.

**Comment by tsuharesu** [comment]
Or use the previous version =P
Thanks anyway :smile:

**Comment by dgreenhalgh** [comment]
Solved in 2.0.0.
