### ISSUE TITLE
How to implemention childView click event?

### ISSUE THREAD

**Issue by 455631680** [bignerdranch/expandable-recycler-view#52]
and get the parent and child data?

**Comment by ThatKawaiiGuy** [comment]
I managed to implement child click events y going to the adapter and adding a clicklistener to child textview. Keep in mind in the XML you should increase the padding of the textview to fill the whole list part, and you should enable 
```
        android:background="?android:attr/selectableItemBackground"
        android:clickable="true"
        android:focusable="true"
```

on to your textview so it has a response to the touch.

Here's the code I used for adding the listener.
The method is from the ExpandableRecyclerAdapter
```
@Override
    public void onBindChildViewHolder(final CustomChildViewHolder childViewHolder, int position, Object childObject) {
        CustomChildObject customChildObject = (CustomChildObject) childObject;
        childViewHolder.dataText.setText(customChildObject.getChildText());
        childViewHolder.dataText.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent mIntent = new Intent(context, FrameDataList.class);
                mIntent.putExtra("character", characterPicked);
                mIntent.putExtra("frame", childViewHolder.dataText.getText());
                context.startActivity(mIntent);

            }
        });
    }
```

**Comment by paul-turner** [comment]
@455631680, @ThatKawaiiGuy has the right idea, you'll need to register an onClick listener on your childView and there you'll have a reference to your child object (which you can store a reference to your parent if you need it).

**Comment by ThatKawaiiGuy** [comment]
Is there a way to prevent duplicate activities being made when the childview is double tapped? I fixed it in other recyclerviews by adding a boolean canStart thats set false when an Activity is created, and then set true in the onResume of the activity with the recyclerview. But since the listener is assigned in the adapter, this method is not possible. Do you have any suggestions?

**Comment by girubhai** [comment]
@paul-turner in onBindChildViewHolder, position parameter is of parent or for child? As I need to get position of parent whose child was clicked.

**Comment by paul-turner** [comment]
@girubhai looks like it is the position for the entire list, including both children and parents for the whole thing. Which I do not like and probably will make an issue to change it. For the mean time you should be able to store that meta-data in the child object maybe?

**Comment by mwshubham** [comment]
Is there any good solution available.

**Comment by knuseski** [comment]
Still not solution about getting parent into childClick ??

**Comment by paul-turner** [comment]
@knuseski Child click has been possible since day one, see the samples with the library or the code given above. 
for @girubhai's question, we have now implemented child position and parent position datain the 3.0.0 snapshot, details are in the issue tracking this effort #157

**Comment by marlonpya** [comment]
```
public interface OnNavigationDrawerListener {

        @UiThread
        void onParentItemClick(NavigationDrawerFatherModel poNavigationDrawerFatherModel, int piPosition);

        @UiThread
        void onChildItemClick(NavigationDrawerSonModel poNavigationDrawerSonModel, int piPosition);
    }

@Override
    public void onBindParentViewHolder(@NonNull DrawerViewHolderFather poDrawerViewHolderFather, final int parentPosition, @NonNull final NavigationDrawerFatherModel poNavigationDrawerFatherModel) {
        poDrawerViewHolderFather.bind(poNavigationDrawerFatherModel);
        poDrawerViewHolderFather.itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                goOnNavigationDrawerListener.onParentItemClick(poNavigationDrawerFatherModel, parentPosition);
            }
        });
    }

    @Override
    public void onBindChildViewHolder(@NonNull DrawerViewHolderSon poDrawerViewHolderSon, int parentPosition, final int childPosition, @NonNull final NavigationDrawerSonModel poNavigationDrawerSonModel) {
        poDrawerViewHolderSon.bind(poNavigationDrawerSonModel);
        poDrawerViewHolderSon.itemView.setOnClickListener(new View.OnClickListener(){
            @Override
            public void onClick(View v) {
                goOnNavigationDrawerListener.onChildItemClick(poNavigationDrawerSonModel, childPosition);
            }
        });
    }
```
