### ISSUE TITLE
Installed library by gradle hasn't ExpandCollapseListener class

### ISSUE THREAD

**Issue by amnazhatdinov** [bignerdranch/expandable-recycler-view#56]
Installed this library by gradle (compile 'com.bignerdranch.android:expandablerecyclerview:1.0.3'). However, cannot implement the ExpandCollapseListener interface because installed library doesn't have this class. How can I deal with this problem?
![issue](https://cloud.githubusercontent.com/assets/5819885/9681123/904796e4-531d-11e5-8390-140fe7d8f19c.jpg)

**Comment by paul-turner** [comment]
@amnazhatdinov You're right, somehow the aar we uploaded doesn't have the ExpandCollapseListener, I'll see what I can do to get it uploaded again with the correct files.

**Comment by florianhenonin** [comment]
Is that bug fixed ?

**Comment by amnazhatdinov** [comment]
No)

2015-09-07 20:49 GMT+06:00 Florian Henonin <notifications@github.com>:

**Comment by paul-turner** [comment]
Found the problem, that class wasn't part of the 1.0.3 release, will be updating the releases here and adding a CHANGELOG for better information. Sorry for the confusion!

In the meantime I've uploaded a snapshot with the current changes in master, try adding the following:
```gradle
compile 'com.bignerdranch.android:expandablerecyclerview:1.1.0-SNAPSHOT'
```
and to your repositories tag in the root build.gradle:
```gradle
allprojects {
    repositories {
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
}
```
