### ISSUE TITLE
Bring mItemList back

### ISSUE THREAD

**Issue by tsuharesu** [bignerdranch/expandable-recycler-view#64]
I just updated and had to revert because I need this variable, or any other way to see the complete list of items on the Adapter.

My use case: I have different ViewTypes, more than just Parent and Child, and I am using this library as my BaseAdapter. But without mItemList I can't get the currentItem on the `onBindViewHolder`, so I can't Override it correctly.

**Comment by paul-turner** [comment]
`mItemList` was renamed to `mHelperItemList`, should still have the same ability you had before. Let me know if that isn't the case!

**Comment by tsuharesu** [comment]
It is private, I can't access with my Adapter
https://github.com/bignerdranch/expandable-recycler-view/blob/master/expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/Adapter/ExpandableRecyclerAdapter.java#L41

**Comment by paul-turner** [comment]
Ah missed that, I tend to default to private when declaring variables.

Would it suit your needs to have 
https://github.com/bignerdranch/expandable-recycler-view/blob/master/expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/Adapter/ExpandableRecyclerAdapter.java#L434
made protected or public in order for you to get the item for a specific index? Or do you need the entire list usually?

**Comment by tsuharesu** [comment]
That would help :)

**Comment by paul-turner** [comment]
Will get that right out.

Was thinking about your use case further today, seems like we could be more flexible in allowing multiple view types of parents and children. Basically by default we can assume 1 and 1, and if the user of the library needs more they can override getChildViewType/getParentViewType and return the types based on their model and we'll pass that information of view type to onCreate/onBind. 
If it doesn't fit your use case directly I think it might still be of benefit for more view types within a list. Thoughts?

**Comment by tsuharesu** [comment]
What I am doing right now is overriding getItemViewType, returning the ViewType of my model.
Then on onCreateViewholder I create the holder I need and overriding onBindViewholder to bind the way I need. If it is not one of my custom viewholders I just use super - that will call parent or child bind.

**Comment by jyoungrok** [comment]
so... what's the result?
