### ISSUE TITLE
Always Expanded ?

### ISSUE THREAD

**Issue by stasbar** [bignerdranch/expandable-recycler-view#66]
Hello. Is it possible to set parent to be always expanded and prevent for collapsing ?

**Comment by paul-turner** [comment]
In the upcoming 2.0.0 release (currently on master) you should be able to override [shouldItemViewClickToggleExpansion](https://github.com/bignerdranch/expandable-recycler-view/blob/master/expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/ViewHolder/ParentViewHolder.java#L101) to return false, and then set your own click listener that calls [toggleExpansion](https://github.com/bignerdranch/expandable-recycler-view/blob/master/expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/ViewHolder/ParentViewHolder.java#L108) only on parent views you want to expand/collapse

**Comment by paul-turner** [comment]
Edited the above to reflect recent changes, let me know if that doesn't work for you. You can check out the snapshot while we work on releasing 2.0.0

**Comment by rinlv** [comment]
Hi Paul,
I'm using version 2.0.3 but the method shouldItemViewClickToggleExpansion() has been deprecated. What is the method replaced it?
Thanks.

**Comment by paul-turner** [comment]
Hi @rinlv,  `shouldItemViewClickToggleExpansion` should still be available in 2.0.3:
https://github.com/bignerdranch/expandable-recycler-view/blob/master/expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/ViewHolder/ParentViewHolder.java#L140

Are you not finding it in your project?

**Comment by rinlv** [comment]
Oh, my mistake, thanks you very much. It's mean, i have override method shouldItemViewClickToggleExpansion on my ParentViewHolder class
