### ISSUE TITLE
Use custom object for parent list?

### ISSUE THREAD

**Issue by tturcic** [bignerdranch/expandable-recycler-view#73]
Hi, currently, parent object must implement ParentObject interface and that interface only accepts a List of Object-s. Is there a way to make custom objects work with it?

**Comment by paul-turner** [comment]
@tturcic the interface accepts a list of Object which will allow you to store a list of your custom objects as needed, see our sample for examples of returning lists of our custom object and then casting when we need to bind the data.

**Comment by tturcic** [comment]
Hey, yeah, I have it working (great lib btw, the easiest one for expandable recyclerview out there). My only problem is that I already have all of my objects in lists of custom objects since I parse all my data from json. So, I have the following:
    
    public class MyObject implements ParentObject, Parcelable {

        @SerializedName("data")
        private List<MySubObject> myList;

        public List<Object> getChildObjectList() {
             // can't return myList here since it is not of type Object
            // instead I have to iterate through my object and create a separate List<Object> ?
        }
    }

Also, a bit unrelated, but 2.0 snapshot doesn't have following methods:
adapter.setCustomParentAnimationViewId(R.id.parent_list_item_expand_arrow);
adapter.setParentClickableViewAnimationDefaultDuration();
adapter.setParentAndIconExpandOnClick(true);

**Comment by paul-turner** [comment]
Glad to hear it's working well for you!

I'll see if there's something we can do to prevent from needing to recreate a list of objects. Probably will have an answer later today.

As for the animation methods, those were in fact removed from the library. We'll have better documentation for changes when we make the official release, for now the samples show the same implementation that you can use to create the same behaviour. Unfortunately we found the animation portion to be overly specific to one implementation, so we focused on giving the user flexibility to do any animation they desire.

**Comment by tturcic** [comment]
Thanks for the quick reply and keep up the good work :)
