### ISSUE TITLE
setExpanded not working

### ISSUE THREAD

**Issue by poldz123** [bignerdranch/expandable-recycler-view#75]
Initializing the parent ViewHolder with setExpanded wont work. 

`@Override
    public void onBindParentViewHolder(OTDFavoriteBusRouteParentExpandableViewHolder otdParent, int i, Object o) {
        OTDExpandableParent parent = (OTDExpandableParent) o;
        parent.setExpanded(true);
        otdParent.parentTitle.setText(parent.getParentTitle());
    }`

And `isInitiallyExpanded` does not exist.

Using 1.0.3

**Comment by paul-turner** [comment]
@poldz123 isInitiallyExpanded was introduced for our 2.0.0 release, a snapshot is available until we make a final release (should be this week)

**Comment by dgreenhalgh** [comment]
Resolved in 2.0.0.
