### ISSUE TITLE
Implement Additional notifyDatasetChanged methods

### ISSUE THREAD

**Issue by paul-turner** [bignerdranch/expandable-recycler-view#88]
Currently ExpandableRecyclerView implements
```java
 // Parent Changes
 notifyParentItemInserted(int parentPosition)}
 notifyParentItemRemoved(int parentPosition)}
 notifyParentItemChanged(int parentPosition)}
 notifyParentItemRangeInserted(int parentPositionStart, int itemCount)}
 // Child Changes
 notifyChildItemInserted(int parentPosition, int childPosition)}
 notifyChildItemRemoved(int parentPosition, int childPosition)}
 notifyChildItemChanged(int parentPosition, int childPosition)}
```

Would be nice to have:
```java
 notifyParentItemRangeRemoved(int parentPositionStart, int itemCount)}
 notifyParentItemRangeChanged(int parentPositionStart, int itemCount)}

 notifyChildItemRangeRemoved(int parentPosition, int childPositionStart, int itemCount)}
 notifyChildItemRangeInserted(int parentPosition, int childPositionStart, int itemCount)}
 notifyChildItemRangeChanged(int parentPosition, int childPositionStart, int itemCount)}

notifyParentItemMoved(int parentFromPosition, int parentToPosition)
notifyChildItemMoved(int parentPosition, int childFromPosition, int childToPosition)
```

**Comment by paul-turner** [comment]
See #98 and #101 for requests related to `notify__ItemMoved` methods

**Comment by paul-turner** [comment]
(To help me keep track)
~~notifyParentItemRangeRemoved(int parentPositionStart, int itemCount)~~ #118
~~notifyParentItemRangeChanged(int parentPositionStart, int itemCount)~~ #118

~~notifyChildItemRangeRemoved(int parentPosition, int childPositionStart, int itemCount)~~ #119
~~notifyChildItemRangeInserted(int parentPosition, int childPositionStart, int itemCount)~~ #119
~~notifyChildItemRangeChanged(int parentPosition, int childPositionStart, int itemCount)~~ #119

notifyParentItemMoved(int parentFromPosition, int parentToPosition)
notifyChildItemMoved(int parentPosition, int childFromPosition, int childToPosition)

**Comment by WonderCsabo** [comment]
I would also suggest a `notifyOnlyParentItemChanged()` and such methods. `notifyParentItemChanged()` also calls `notifyItemChanged()` for all children. This maybe the general case (but i am not sure even about that), however in my app this is not the case. It would be useful to provide such methods.

**Comment by paul-turner** [comment]
Thanks @WonderCsabo, I'll consider maybe adding a flag as to whether children should reload or not as well.

**Comment by paul-turner** [comment]
Implemented additional methods, do not yet have flag to optimize case where children do not need to change (will create a new issue for that)
