### ISSUE TITLE
Support notifyDataSetChanged()

### ISSUE THREAD

**Issue by paul-turner** [bignerdranch/expandable-recycler-view#89]
Allow the user to change the entire list and notify the adapter that the dataset is changed.

In order to do this we will need to implement and idea of stableId's for the items to preserve expanded state.

**Comment by rafaelmeteoro** [comment]
Any idea how to do or when it will be ready?

**Comment by paul-turner** [comment]
We will try to get to this soon.
As for how, it will require that each parentItem have a unique identifier so that we can save the expanded state between changes and then apply it to the new items where some of the items are equal.

**Comment by silviahisham** [comment]
When will this be ready please?

**Comment by dgreenhalgh** [comment]
@silviahisham We don't currently have an estimate, but this is a top priority once we have the availability.

**Comment by neteinstein** [comment]
+1

**Comment by bene25** [comment]
+1

**Comment by goonerDroid** [comment]
Is there any update on this??. notifyDataSetChanged() equivalent is a required and an urgent feature.

**Comment by Ajibola** [comment]
+1

**Comment by paul-turner** [comment]
Hello, we've released 3.0.0-RC1 with a fix for this issue. 

I would love your feedback with any issues you have with the solution before we make 3.0.0 final. Check out the Pull Request that contains the fix for your issue (should be referenced above), and the [changelog](https://github.com/bignerdranch/expandable-recycler-view/releases/tag/v3.0.0-RC1) for a list of changes that have come with 3.0.0 (there are a lot of them!). 

If you have any issues feel free to re-open this issue with details of what you are seeing.

**Comment by mahmooddagga** [comment]
notifyDataSetChanged Not Working

**Comment by KostyaBakay** [comment]
List is still collapsing after update. Did somebody fix this issue?
