### ISSUE TITLE
Showing child view

### ISSUE THREAD

**Issue by lukachuuu** [bignerdranch/expandable-recycler-view#92]
Hi

I have one question, how i can display sometimes only child view? (like ParentItem, ParentItem, ChildItem, ParentItem...).
I try in ItemCellParentViewHolder return child view but this way i make a lot of problems.

Is it possible?

Ty

Luka

**Comment by paul-turner** [comment]
Hi @lukachuuu,
We don't currently have the ability to show a parentless child easily. You could extend the adapter and extend `onBindViewHolder` and `onCreateViewHolder` and `getItemViewType` to return a third type of view and handle that before calling super.
Will having multiple parent view types make this simpler for you (considering this for a future release)?

**Comment by lukachuuu** [comment]
I have a lot of similarities between parent and child view, then I in  `onBindParentViewHolder` method checking if `parentItem` have child. If have child show dropdown button if haven't don't show. This solution is very amiss but is working.

I will try to create third type of view and return before call `super` method. This solution sounds simple.
Thank you for your response. L
