### ISSUE TITLE
Problems with notifyParentItemRangeInserted

### ISSUE THREAD

**Issue by rafaelmeteoro** [bignerdranch/expandable-recycler-view#93]
I have a list of 20 parent elements. I load 12 elements and add all at the end of list with addAll. After this call notifyParentItemInserted (20,12) but not so no modifications and log appears an error indexOfBounds. How do I notify you insert several items on my list?

**Comment by paul-turner** [comment]
Hi @rafaelmeteoro, You are using the right API to do what you want, any chance you could show the snippet where you add the items and call notifyParentItemInserted, as well as the stacktrace of your error?

**Comment by rafaelmeteoro** [comment]
Hello. I meant notifyParentItemRangeInserted and not notifyParentItemInserted, but I think you get the idea.

This method receives a list of items to be entered, take the size of the current list, then adds the items received at the end of the list with addAll and finally notifies the change with notifyParentItemRangeInserted passing the inserted position parameters and the entered quantity.

public void addRfids(List<Rfid> newRfids) {
        int parentPositionStartInserted = getItemCount();
        this.rfids.addAll(newRfids);
        notifyParentItemRangeInserted(parentPositionStartInserted, newRfids.size());
    }

The error code snippet I get is:

10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event: Could not dispatch event: class br.com.wari.wari.event.RfidsSuccessEvent to subscribing class class br.com.wari.wari.mvp.presenter.ParticipantePresenter
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event: java.lang.IndexOutOfBoundsException: Invalid index -1, size is 20
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at java.util.ArrayList.add(ArrayList.java:143)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at com.bignerdranch.expandablerecyclerview.Adapter.ExpandableRecyclerAdapter.addParentWrapper(ExpandableRecyclerAdapter.java:691)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at com.bignerdranch.expandablerecyclerview.Adapter.ExpandableRecyclerAdapter.notifyParentItemRangeInserted(ExpandableRecyclerAdapter.java:680)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at br.com.wari.wari.adapter.ParticipantesExpandleAdapter.addRfids(ParticipantesExpandleAdapter.java:73)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at br.com.wari.wari.activity.ParticipantesFragment.addData(ParticipantesFragment.java:178)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at br.com.wari.wari.mvp.presenter.ParticipantePresenter.onEvent(ParticipantePresenter.java:73)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at java.lang.reflect.Method.invokeNative(Native Method)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at java.lang.reflect.Method.invoke(Method.java:511)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:498)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at de.greenrobot.event.EventBus.postToSubscription(EventBus.java:429)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at de.greenrobot.event.EventBus.postSingleEventForEventType(EventBus.java:410)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at de.greenrobot.event.EventBus.postSingleEvent(EventBus.java:383)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at de.greenrobot.event.EventBus.post(EventBus.java:263)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at br.com.wari.wari.network.RfidRestService$2.success(RfidRestService.java:39)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at br.com.wari.wari.network.RfidRestService$2.success(RfidRestService.java:35)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at android.os.Handler.handleCallback(Handler.java:615)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at android.os.Handler.dispatchMessage(Handler.java:92)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at android.os.Looper.loop(Looper.java:137)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at android.app.ActivityThread.main(ActivityThread.java:4745)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at java.lang.reflect.Method.invokeNative(Native Method)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at java.lang.reflect.Method.invoke(Method.java:511)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
10-05 10:45:39.715 21800-21800/br.com.wari.wari E/Event:     at dalvik.system.NativeStart.main(Native Method)

Sorry for my English

**Comment by paul-turner** [comment]
@rafaelmeteoro Got it, definitely a bug on our end, will try and get a fix out today

**Comment by rafaelmeteoro** [comment]
@paul-turner Thank you, it worked fine
