### ISSUE TITLE
disable first item expanded mode?

### ISSUE THREAD

**Issue by TheLoyalCruel** [bignerdranch/expandable-recycler-view#99]
when the list is started the first item is expanded... how to disable it?
I want all items to be collapsed on start...
thanks

**Comment by paul-turner** [comment]
@TheLoyalCruel I assume you are using one of the examples as your starting point. You'll see that the `ParentListItem` has the method `isInitiallyExpanded`, we set that to true for the first item [here](https://github.com/bignerdranch/expandable-recycler-view/blob/master/app/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/vertical/VerticalLinearRecyclerViewSampleActivity.java#L135), you can remove that line, or make your objects always return false for that method.

Let me know if that helps you.

**Comment by TheLoyalCruel** [comment]
thanks alot... it is really helpful :)

**Comment by paul-turner** [comment]
No problem
